SELECT
    MANDT AS CLIENT,
    BUKRS AS COMPANY_CODE,
    BELNR AS DOCUMENT_NUMBER,
    GJAHR AS FISCAL_YEAR,
    BLART AS DOCUMENT_TYPE,
    BUDAT AS POSTING_DATE,
    BLDAT AS DOCUMENT_DATE,
    WAERS AS CURRENCY,
    USNAM AS USER_NAME
FROM {{ source('sap_ecc', 'BKPF') }}
