SELECT
    MANDT AS CLIENT,
    BUKRS AS COMPANY_CODE,
    ANLN1 AS ASSET_NUMBER,
    ANLN2 AS ASSET_SUBNUMBER,
    ANLKL AS ASSET_CLASS,
    TXT50 AS ASSET_DESCRIPTION,
    AKTIV AS CAPITALIZATION_DATE,
    DEAKT AS DEACTIVATION_DATE,
    KOSTL AS COST_CENTER,
    WERKS AS PLANT
FROM {{ source('sap_ecc', 'ANLA') }}
