SELECT
    MANDT AS CLIENT,
    VBELN AS BILLING_DOCUMENT_NUMBER,
    FKART AS BILLING_TYPE,
    FKDAT AS BILLING_DATE,
    KUNRG AS PAYER_CUSTOMER,
    KUNAG AS SOLD_TO_CUSTOMER,
    VKORG AS SALES_ORGANIZATION,
    VTWEG AS DISTRIBUTION_CHANNEL,
    SPART AS DIVISION,
    NETWR AS NET_VALUE,
    MWSBK AS TAX_AMOUNT,
    WAERK AS CURRENCY,
    BUKRS AS COMPANY_CODE,
    LAND1 AS COUNTRY,
    RFBSK AS ACCOUNTING_STATUS,
    ERDAT AS CREATED_DATE,
    ERNAM AS CREATED_BY
FROM {{ source('sap_ecc', 'VBRK') }}
