SELECT
    ms.MANDT AS CLIENT,
    ms.MBLNR AS DOCUMENT_NUMBER,
    ms.MJAHR AS FISCAL_YEAR,
    ms.ZEILE AS ITEM_NUMBER,
    ms.BWART AS MOVEMENT_TYPE,
    ms.MATNR AS MATERIAL_NUMBER,
    ms.WERKS AS PLANT_CODE,
    ms.LGORT AS STORAGE_LOCATION,
    ms.CHARG AS BATCH_NUMBER,
    ms.MENGE AS QUANTITY,
    ms.MEINS AS UNIT_OF_MEASURE,
    ms.DMBTR AS AMOUNT_LOCAL,
    ms.WAERS AS CURRENCY,
    ms.SHKZG AS DEBIT_CREDIT_IND,
    ms.SOBKZ AS SPECIAL_STOCK_IND,
    ms.LIFNR AS VENDOR_NUMBER,
    ms.KUNNR AS CUSTOMER_NUMBER,
    ms.AUFNR AS ORDER_NUMBER,
    ms.KOSTL AS COST_CENTER,
    mk.BUDAT AS POSTING_DATE,
    mk.CPUDT AS ENTRY_DATE,
    mk.USNAM AS CREATED_BY
FROM {{ source('sap_ecc', 'MSEG') }} ms
LEFT JOIN {{ source('sap_ecc', 'MKPF') }} mk
    ON ms.MANDT = mk.MANDT AND ms.MBLNR = mk.MBLNR AND ms.MJAHR = mk.MJAHR
