SELECT
    MANDT AS CLIENT,
    PERNR AS PERSONNEL_NUMBER,
    ENDDA AS END_DATE,
    BEGDA AS START_DATE,
    MASSN AS ACTION_TYPE,
    MASSG AS ACTION_REASON,
    STAT2 AS EMPLOYMENT_STATUS
FROM {{ source('sap_ecc', 'PA0000') }}
