SELECT
    MANDT AS CLIENT,
    PERNR AS PERSONNEL_NUMBER,
    ENDDA AS END_DATE,
    BEGDA AS START_DATE,
    SUBTY AS ABSENCE_TYPE,
    ABESSION AS ABSENCE_HOURS
FROM {{ source('sap_ecc', 'PA2001') }}
