SELECT
    MANDT AS CLIENT,
    PERNR AS PERSONNEL_NUMBER,
    ENDDA AS END_DATE,
    BEGDA AS START_DATE,
    TRFAR AS PAY_SCALE_TYPE,
    TRFGB AS PAY_SCALE_AREA,
    TRFGR AS PAY_SCALE_GROUP,
    TRFST AS PAY_SCALE_LEVEL,
    ANSAL AS ANNUAL_SALARY,
    WAESSION AS CURRENCY
FROM {{ source('sap_ecc', 'PA0008') }}
