SELECT
    m.MANDT AS CLIENT,
    m.MATNR AS MATERIAL_NUMBER,
    t.MAKTX AS MATERIAL_DESCRIPTION,
    m.MTART AS MATERIAL_TYPE,
    m.MATKL AS MATERIAL_GROUP,
    m.MEINS AS BASE_UNIT_OF_MEASURE,
    m.BRGEW AS GROSS_WEIGHT,
    m.NTGEW AS NET_WEIGHT,
    m.GEWEI AS WEIGHT_UNIT,
    m.SPART AS DIVISION,
    m.PRDHA AS PRODUCT_HIERARCHY,
    m.BISMT AS OLD_MATERIAL_NUMBER,
    m.MSTAE AS CROSS_PLANT_STATUS,
    m.ERNAM AS CREATED_BY,
    m.LAEDA AS LAST_CHANGE_DATE
FROM {{ source('sap_ecc', 'MARA') }} m
LEFT JOIN {{ source('sap_ecc', 'MAKT') }} t
    ON m.MANDT = t.MANDT AND m.MATNR = t.MATNR
