SELECT
    MANDT AS CLIENT,
    MATNR AS MATERIAL_NUMBER,
    WERKS AS PLANT_CODE,
    DISGR AS MRP_GROUP,
    DISPO AS MRP_CONTROLLER,
    DISMM AS MRP_TYPE,
    FHORI AS SCHEDULING_MARGIN_KEY,
    EKGRP AS PURCHASING_GROUP,
    MMSTA AS PLANT_MATERIAL_STATUS,
    MAABC AS ABC_INDICATOR,
    BESKZ AS PROCUREMENT_TYPE,
    SOBSL AS SPECIAL_PROCUREMENT,
    MINBE AS REORDER_POINT,
    MABST AS MAX_STOCK_LEVEL,
    LOSGR AS LOT_SIZE,
    PLIFZ AS PLANNED_DELIVERY_TIME,
    WEBAZ AS GR_PROCESSING_TIME
FROM {{ source('sap_ecc', 'MARC') }}
