SELECT
    j.MANDT AS CLIENT,
    j.OBJNR AS OBJECT_NUMBER,
    j.STAT AS STATUS,
    j.INACT AS INACTIVE_FLAG,
    t.TXT04 AS STATUS_SHORT_TEXT,
    t.TXT30 AS STATUS_DESCRIPTION
FROM {{ source('sap_ecc', 'JEST') }} j
LEFT JOIN {{ source('sap_ecc', 'TJ02T') }} t
    ON j.MANDT = t.MANDT AND j.STAT = t.ISTAT
    AND t.SPRAS = 'E'
