SELECT
    MANDT AS CLIENT,
    EBELN AS PO_NUMBER,
    EBELP AS ITEM_NUMBER,
    ETENR AS SCHEDULE_LINE_NUMBER,
    EINDT AS DELIVERY_DATE,
    MENGE AS SCHEDULED_QUANTITY,
    WEMNG AS DELIVERED_QUANTITY,
    SLFDT AS STATISTICS_DATE,
    BANFN AS REQUISITION_NUMBER,
    BNFPO AS REQUISITION_ITEM
FROM {{ source('sap_ecc', 'EKET') }}
