SELECT
    g.MANDT AS CLIENT,
    g.INFNR AS INFO_RECORD_NUMBER,
    g.MATNR AS MATERIAL_NUMBER,
    g.LIFNR AS VENDOR_NUMBER,
    g.LOEKZ AS DELETION_INDICATOR,
    o.EKORG AS PURCHASING_ORGANIZATION,
    o.WERKS AS PLANT,
    o.NETPR AS NET_PRICE,
    o.WAERS AS CURRENCY,
    o.PEINH AS PRICE_UNIT
FROM {{ source('sap_ecc', 'EINA') }} g
LEFT JOIN {{ source('sap_ecc', 'EINE') }} o
    ON g.MANDT = o.MANDT AND g.INFNR = o.INFNR
