SELECT
    MANDT AS CLIENT,
    VBELN AS SALES_ORDER_NUMBER,
    GBSTK AS OVERALL_STATUS,
    LFSTK AS DELIVERY_STATUS,
    FKSTK AS BILLING_STATUS,
    ABSTK AS REJECTION_STATUS,
    BESTK AS CONFIRMATION_STATUS,
    COSTA AS ORDER_COMPLETION_STATUS,
    UVALL AS OVERALL_PROCESSING
FROM {{ source('sap_ecc', 'VBUK') }}
