SELECT
    MANDT AS CLIENT,
    TKNUM AS SHIPMENT_NUMBER,
    SDABW AS SPECIAL_PROCESSING,
    VSART AS SHIPPING_TYPE,
    TDLNR AS FORWARDING_AGENT,
    DESSION AS SHIPMENT_DATE
FROM {{ source('sap_ecc', 'VTTK') }}
