SELECT
    MANDT AS CLIENT,
    LIFNR AS VENDOR_NUMBER,
    NAME1 AS VENDOR_NAME,
    NAME2 AS VENDOR_NAME_2,
    LAND1 AS COUNTRY,
    ORT01 AS CITY,
    PSTLZ AS POSTAL_CODE,
    REGIO AS REGION,
    STRAS AS STREET,
    TELF1 AS TELEPHONE,
    SPRAS AS LANGUAGE,
    KTOKK AS ACCOUNT_GROUP,
    LOEVM AS DELETION_FLAG,
    ERDAT AS CREATED_DATE,
    ERNAM AS CREATED_BY
FROM {{ source('sap_ecc', 'LFA1') }}
