SELECT
    MANDT AS CLIENT,
    LIFNR AS VENDOR_NUMBER,
    BUKRS AS COMPANY_CODE,
    PERNR AS PERSONNEL_NUMBER,
    ERDAT AS CREATED_DATE,
    ERNAM AS CREATED_BY,
    AKONT AS RECONCILIATION_ACCOUNT,
    ZUESSION AS SORT_KEY,
    ZTERM AS PAYMENT_TERMS
FROM {{ source('sap_ecc', 'LFB1') }}
