version: 2

sources:
  - name: sap_ecc
    database: SAP
    schema: SAP_ECC
    tables:
      - name: AFKO
      - name: AFPO
      - name: AFVC
      - name: AFVV
      - name: AGR_TEXTS
      - name: AGR_USERS
      - name: ANEP
      - name: ANLA
      - name: AUFK
      - name: BALDAT
      - name: BALHDR
      - name: BDCP2
      - name: BKPF
      - name: BSAD
      - name: BSAK
      - name: BSAS
      - name: BSEG
      - name: BSID
      - name: BSIK
      - name: CDHDR
      - name: CDPOS
      - name: CE1XXXX
      - name: CE2XXXX
      - name: COBK
      - name: COEP
      - name: COSP
      - name: COSS
      - name: CRHD
      - name: CRTX
      - name: CSKA
      - name: CSKB
      - name: CSKS
      - name: CSKT
      - name: CSKU
      - name: DD02L
      - name: DD03L
      - name: EBAN
      - name: EDID4
      - name: EDIDC
      - name: EINA
      - name: EINE
      - name: EKBE
      - name: EKET
      - name: EKKO
      - name: EKPO
      - name: FAGLFLEXA
      - name: HRP1000
      - name: HRP1001
      - name: HRP1002
      - name: INFO
      - name: JEST
      - name: KEKO
      - name: KEPH
      - name: KNA1
      - name: KNVV
      - name: KONV
      - name: LAGP
      - name: LEIN
      - name: LFA1
      - name: LFB1
      - name: LFM1
      - name: LIKP
      - name: LIPS
      - name: LQUA
      - name: LTAK
      - name: LTAP
      - name: LTBK
      - name: LTBP
      - name: MAKT
      - name: MAPL
      - name: MARA
      - name: MARC
      - name: MARD
      - name: MAST
      - name: MDKP
      - name: MDTB
      - name: MKPF
      - name: MLCD
      - name: MSEG
      - name: OBJK
      - name: PA0000
      - name: PA0001
      - name: PA0002
      - name: PA0006
      - name: PA0007
      - name: PA0008
      - name: PA0014
      - name: PA0015
      - name: PA2001
      - name: PA2002
      - name: PA2006
      - name: PBED
      - name: PBIM
      - name: PLAF
      - name: PLKO
      - name: PLPO
      - name: QMEL
      - name: RBKP
      - name: RESB
      - name: RLGRAP
      - name: RSEG
      - name: SER01
      - name: STKO
      - name: STPO
      - name: T000
      - name: T000T
      - name: T001L
      - name: T001W
      - name: T156
      - name: T156T
      - name: T161
      - name: T161T
      - name: T300
      - name: T300T
      - name: T527X
      - name: T529T
      - name: T552T
      - name: T554T
      - name: T556T
      - name: T685
      - name: T685T
      - name: TBDLS
      - name: TCURC
      - name: TCURT
      - name: TCURX
      - name: TJ02
      - name: TJ02T
      - name: TKA01
      - name: TKT01
      - name: TTDS
      - name: TTDST
      - name: TVAK
      - name: TVAKT
      - name: TVAP
      - name: TVAPT
      - name: TVLK
      - name: TVLKT
      - name: USR02
      - name: VBAK
      - name: VBAP
      - name: VBEP
      - name: VBFA
      - name: VBKD
      - name: VBPA
      - name: VBRK
      - name: VBRP
      - name: VBUK
      - name: VBUP
      - name: VFKN
      - name: VFKP
      - name: VTFA
      - name: VTTK
      - name: VTTP
      - name: VTTS
