-- ============================================================================
-- GENERATE SAP SYSTEM - SAP.SAP_ECC
-- Creates SAP ECC tables with primary/foreign keys and generates
-- 100,000 orders with consistent sample data across all related tables
-- ============================================================================

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS SAP;
CREATE SCHEMA IF NOT EXISTS SAP.SAP_ECC;
USE SCHEMA SAP.SAP_ECC;

-- ============================================================================
-- MASTER DATA TABLES
-- ============================================================================

-- T001W: Plants
CREATE OR REPLACE TABLE SAP.SAP_ECC.T001W (
    MANDT VARCHAR(3) DEFAULT '800',
    WERKS VARCHAR(4) NOT NULL,
    NAME1 VARCHAR(30),
    BUKRS VARCHAR(4),
    LAND1 VARCHAR(3),
    CONSTRAINT PK_T001W PRIMARY KEY (MANDT, WERKS)
);

-- KNA1: Customer Master (General)
CREATE OR REPLACE TABLE SAP.SAP_ECC.KNA1 (
    MANDT VARCHAR(3) DEFAULT '800',
    KUNNR VARCHAR(10) NOT NULL,
    NAME1 VARCHAR(35),
    LAND1 VARCHAR(3),
    ORT01 VARCHAR(35),
    PSTLZ VARCHAR(10),
    STRAS VARCHAR(35),
    CONSTRAINT PK_KNA1 PRIMARY KEY (MANDT, KUNNR)
);

-- KNVV: Customer Master (Sales)
CREATE OR REPLACE TABLE SAP.SAP_ECC.KNVV (
    MANDT VARCHAR(3) DEFAULT '800',
    KUNNR VARCHAR(10) NOT NULL,
    VKORG VARCHAR(4) NOT NULL,
    VTWEG VARCHAR(2) NOT NULL,
    SPART VARCHAR(2) NOT NULL,
    KDGRP VARCHAR(2),
    WAERS VARCHAR(5),
    CONSTRAINT PK_KNVV PRIMARY KEY (MANDT, KUNNR, VKORG, VTWEG, SPART),
    CONSTRAINT FK_KNVV_KNA1 FOREIGN KEY (MANDT, KUNNR) REFERENCES SAP.SAP_ECC.KNA1 (MANDT, KUNNR)
);

-- LFA1: Vendor Master
CREATE OR REPLACE TABLE SAP.SAP_ECC.LFA1 (
    MANDT VARCHAR(3) DEFAULT '800',
    LIFNR VARCHAR(10) NOT NULL,
    NAME1 VARCHAR(35),
    LAND1 VARCHAR(3),
    ORT01 VARCHAR(35),
    PSTLZ VARCHAR(10),
    CONSTRAINT PK_LFA1 PRIMARY KEY (MANDT, LIFNR)
);

-- MARA: Material Master (General)
CREATE OR REPLACE TABLE SAP.SAP_ECC.MARA (
    MANDT VARCHAR(3) DEFAULT '800',
    MATNR VARCHAR(18) NOT NULL,
    MTART VARCHAR(4),
    MBRSH VARCHAR(1),
    MATKL VARCHAR(9),
    MEINS VARCHAR(3),
    BRGEW NUMBER(13,3),
    GEWEI VARCHAR(3),
    ERDAT DATE,
    CONSTRAINT PK_MARA PRIMARY KEY (MANDT, MATNR)
);

-- MAKT: Material Descriptions
CREATE OR REPLACE TABLE SAP.SAP_ECC.MAKT (
    MANDT VARCHAR(3) DEFAULT '800',
    MATNR VARCHAR(18) NOT NULL,
    SPRAS VARCHAR(1) NOT NULL,
    MAKTX VARCHAR(40),
    CONSTRAINT PK_MAKT PRIMARY KEY (MANDT, MATNR, SPRAS),
    CONSTRAINT FK_MAKT_MARA FOREIGN KEY (MANDT, MATNR) REFERENCES SAP.SAP_ECC.MARA (MANDT, MATNR)
);

-- MARC: Material Master (Plant Data)
CREATE OR REPLACE TABLE SAP.SAP_ECC.MARC (
    MANDT VARCHAR(3) DEFAULT '800',
    MATNR VARCHAR(18) NOT NULL,
    WERKS VARCHAR(4) NOT NULL,
    DISMM VARCHAR(2),
    DISPO VARCHAR(3),
    BESKZ VARCHAR(1),
    SOBSL VARCHAR(2),
    CONSTRAINT PK_MARC PRIMARY KEY (MANDT, MATNR, WERKS),
    CONSTRAINT FK_MARC_MARA FOREIGN KEY (MANDT, MATNR) REFERENCES SAP.SAP_ECC.MARA (MANDT, MATNR),
    CONSTRAINT FK_MARC_T001W FOREIGN KEY (MANDT, WERKS) REFERENCES SAP.SAP_ECC.T001W (MANDT, WERKS)
);

-- MARD: Material Master (Storage Location)
CREATE OR REPLACE TABLE SAP.SAP_ECC.MARD (
    MANDT VARCHAR(3) DEFAULT '800',
    MATNR VARCHAR(18) NOT NULL,
    WERKS VARCHAR(4) NOT NULL,
    LGORT VARCHAR(4) NOT NULL,
    LABST NUMBER(13,3),
    INSME NUMBER(13,3),
    SPEME NUMBER(13,3),
    CONSTRAINT PK_MARD PRIMARY KEY (MANDT, MATNR, WERKS, LGORT),
    CONSTRAINT FK_MARD_MARC FOREIGN KEY (MANDT, MATNR, WERKS) REFERENCES SAP.SAP_ECC.MARC (MANDT, MATNR, WERKS)
);

-- ============================================================================
-- SALES ORDER TABLES (SD)
-- ============================================================================

-- VBAK: Sales Document Header
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBAK (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    AUART VARCHAR(4),
    VKORG VARCHAR(4),
    VTWEG VARCHAR(2),
    SPART VARCHAR(2),
    KUNNR VARCHAR(10),
    ERDAT DATE,
    NETWR NUMBER(15,2),
    WAERK VARCHAR(5),
    CONSTRAINT PK_VBAK PRIMARY KEY (MANDT, VBELN),
    CONSTRAINT FK_VBAK_KNA1 FOREIGN KEY (MANDT, KUNNR) REFERENCES SAP.SAP_ECC.KNA1 (MANDT, KUNNR)
);

-- VBAP: Sales Document Item
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBAP (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    POSNR VARCHAR(6) NOT NULL,
    MATNR VARCHAR(18),
    KWMENG NUMBER(13,3),
    VRKME VARCHAR(3),
    NETWR NUMBER(15,2),
    WERKS VARCHAR(4),
    CONSTRAINT PK_VBAP PRIMARY KEY (MANDT, VBELN, POSNR),
    CONSTRAINT FK_VBAP_VBAK FOREIGN KEY (MANDT, VBELN) REFERENCES SAP.SAP_ECC.VBAK (MANDT, VBELN),
    CONSTRAINT FK_VBAP_MARA FOREIGN KEY (MANDT, MATNR) REFERENCES SAP.SAP_ECC.MARA (MANDT, MATNR)
);

-- VBEP: Sales Document Schedule Line
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBEP (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    POSNR VARCHAR(6) NOT NULL,
    ETENR VARCHAR(4) NOT NULL,
    EDATU DATE,
    WMENG NUMBER(13,3),
    VRKME VARCHAR(3),
    CONSTRAINT PK_VBEP PRIMARY KEY (MANDT, VBELN, POSNR, ETENR),
    CONSTRAINT FK_VBEP_VBAP FOREIGN KEY (MANDT, VBELN, POSNR) REFERENCES SAP.SAP_ECC.VBAP (MANDT, VBELN, POSNR)
);

-- VBKD: Sales Document Business Data
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBKD (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    POSNR VARCHAR(6) NOT NULL,
    ZTERM VARCHAR(4),
    INCO1 VARCHAR(3),
    INCO2 VARCHAR(28),
    CONSTRAINT PK_VBKD PRIMARY KEY (MANDT, VBELN, POSNR),
    CONSTRAINT FK_VBKD_VBAK FOREIGN KEY (MANDT, VBELN) REFERENCES SAP.SAP_ECC.VBAK (MANDT, VBELN)
);

-- VBPA: Sales Document Partner
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBPA (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    POSNR VARCHAR(6) NOT NULL,
    PARVW VARCHAR(2) NOT NULL,
    KUNNR VARCHAR(10),
    LIFNR VARCHAR(10),
    CONSTRAINT PK_VBPA PRIMARY KEY (MANDT, VBELN, POSNR, PARVW),
    CONSTRAINT FK_VBPA_VBAK FOREIGN KEY (MANDT, VBELN) REFERENCES SAP.SAP_ECC.VBAK (MANDT, VBELN)
);

-- VBUK: Sales Document Header Status
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBUK (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    GBSTK VARCHAR(1),
    LFSTK VARCHAR(1),
    CONSTRAINT PK_VBUK PRIMARY KEY (MANDT, VBELN),
    CONSTRAINT FK_VBUK_VBAK FOREIGN KEY (MANDT, VBELN) REFERENCES SAP.SAP_ECC.VBAK (MANDT, VBELN)
);

-- VBUP: Sales Document Item Status
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBUP (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    POSNR VARCHAR(6) NOT NULL,
    GBSTA VARCHAR(1),
    LFSTA VARCHAR(1),
    CONSTRAINT PK_VBUP PRIMARY KEY (MANDT, VBELN, POSNR),
    CONSTRAINT FK_VBUP_VBAP FOREIGN KEY (MANDT, VBELN, POSNR) REFERENCES SAP.SAP_ECC.VBAP (MANDT, VBELN, POSNR)
);

-- VBFA: Sales Document Flow
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBFA (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELV VARCHAR(10) NOT NULL,
    POSNV VARCHAR(6) NOT NULL,
    VBELN VARCHAR(10) NOT NULL,
    POSNN VARCHAR(6) NOT NULL,
    VBTYP_N VARCHAR(1),
    ERDAT DATE,
    CONSTRAINT PK_VBFA PRIMARY KEY (MANDT, VBELV, POSNV, VBELN, POSNN)
);

-- KONV: Sales Document Conditions
CREATE OR REPLACE TABLE SAP.SAP_ECC.KONV (
    MANDT VARCHAR(3) DEFAULT '800',
    KNUMV VARCHAR(10) NOT NULL,
    KPOSN VARCHAR(6) NOT NULL,
    STUNR VARCHAR(3) NOT NULL,
    ZAEHK VARCHAR(2) NOT NULL,
    KSCHL VARCHAR(4),
    KBETR NUMBER(11,2),
    WAERS VARCHAR(5),
    KWERT NUMBER(15,2),
    CONSTRAINT PK_KONV PRIMARY KEY (MANDT, KNUMV, KPOSN, STUNR, ZAEHK)
);

-- ============================================================================
-- DELIVERY TABLES (LE)
-- ============================================================================

-- LIKP: Delivery Header
CREATE OR REPLACE TABLE SAP.SAP_ECC.LIKP (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    LFART VARCHAR(4),
    KUNNR VARCHAR(10),
    WADAT DATE,
    CONSTRAINT PK_LIKP PRIMARY KEY (MANDT, VBELN),
    CONSTRAINT FK_LIKP_KNA1 FOREIGN KEY (MANDT, KUNNR) REFERENCES SAP.SAP_ECC.KNA1 (MANDT, KUNNR)
);

-- LIPS: Delivery Item
CREATE OR REPLACE TABLE SAP.SAP_ECC.LIPS (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    POSNR VARCHAR(6) NOT NULL,
    MATNR VARCHAR(18),
    LFIMG NUMBER(13,3),
    VRKME VARCHAR(3),
    WERKS VARCHAR(4),
    CONSTRAINT PK_LIPS PRIMARY KEY (MANDT, VBELN, POSNR),
    CONSTRAINT FK_LIPS_LIKP FOREIGN KEY (MANDT, VBELN) REFERENCES SAP.SAP_ECC.LIKP (MANDT, VBELN),
    CONSTRAINT FK_LIPS_MARA FOREIGN KEY (MANDT, MATNR) REFERENCES SAP.SAP_ECC.MARA (MANDT, MATNR)
);

-- ============================================================================
-- BILLING TABLES (SD-BIL)
-- ============================================================================

-- VBRK: Billing Document Header
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBRK (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    FKART VARCHAR(4),
    KUNNR VARCHAR(10),
    FKDAT DATE,
    NETWR NUMBER(15,2),
    WAERK VARCHAR(5),
    CONSTRAINT PK_VBRK PRIMARY KEY (MANDT, VBELN),
    CONSTRAINT FK_VBRK_KNA1 FOREIGN KEY (MANDT, KUNNR) REFERENCES SAP.SAP_ECC.KNA1 (MANDT, KUNNR)
);

-- VBRP: Billing Document Item
CREATE OR REPLACE TABLE SAP.SAP_ECC.VBRP (
    MANDT VARCHAR(3) DEFAULT '800',
    VBELN VARCHAR(10) NOT NULL,
    POSNR VARCHAR(6) NOT NULL,
    MATNR VARCHAR(18),
    FKIMG NUMBER(13,3),
    VRKME VARCHAR(3),
    NETWR NUMBER(15,2),
    CONSTRAINT PK_VBRP PRIMARY KEY (MANDT, VBELN, POSNR),
    CONSTRAINT FK_VBRP_VBRK FOREIGN KEY (MANDT, VBELN) REFERENCES SAP.SAP_ECC.VBRK (MANDT, VBELN),
    CONSTRAINT FK_VBRP_MARA FOREIGN KEY (MANDT, MATNR) REFERENCES SAP.SAP_ECC.MARA (MANDT, MATNR)
);

-- ============================================================================
-- PURCHASING TABLES (MM)
-- ============================================================================

-- EKKO: Purchase Order Header
CREATE OR REPLACE TABLE SAP.SAP_ECC.EKKO (
    MANDT VARCHAR(3) DEFAULT '800',
    EBELN VARCHAR(10) NOT NULL,
    BUKRS VARCHAR(4),
    BSTYP VARCHAR(1),
    BSART VARCHAR(4),
    LIFNR VARCHAR(10),
    EKORG VARCHAR(4),
    BEDAT DATE,
    WAERS VARCHAR(5),
    CONSTRAINT PK_EKKO PRIMARY KEY (MANDT, EBELN),
    CONSTRAINT FK_EKKO_LFA1 FOREIGN KEY (MANDT, LIFNR) REFERENCES SAP.SAP_ECC.LFA1 (MANDT, LIFNR)
);

-- EKPO: Purchase Order Item
CREATE OR REPLACE TABLE SAP.SAP_ECC.EKPO (
    MANDT VARCHAR(3) DEFAULT '800',
    EBELN VARCHAR(10) NOT NULL,
    EBELP VARCHAR(5) NOT NULL,
    MATNR VARCHAR(18),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    NETPR NUMBER(11,2),
    WERKS VARCHAR(4),
    LIFNR VARCHAR(10),
    CONSTRAINT PK_EKPO PRIMARY KEY (MANDT, EBELN, EBELP),
    CONSTRAINT FK_EKPO_EKKO FOREIGN KEY (MANDT, EBELN) REFERENCES SAP.SAP_ECC.EKKO (MANDT, EBELN),
    CONSTRAINT FK_EKPO_MARA FOREIGN KEY (MANDT, MATNR) REFERENCES SAP.SAP_ECC.MARA (MANDT, MATNR)
);

-- ============================================================================
-- FINANCE TABLES (FI)
-- ============================================================================

-- BKPF: Accounting Document Header
CREATE OR REPLACE TABLE SAP.SAP_ECC.BKPF (
    MANDT VARCHAR(3) DEFAULT '800',
    BUKRS VARCHAR(4) NOT NULL,
    BELNR VARCHAR(10) NOT NULL,
    GJAHR VARCHAR(4) NOT NULL,
    BLART VARCHAR(2),
    BUDAT DATE,
    BLDAT DATE,
    WAERS VARCHAR(5),
    USNAM VARCHAR(12),
    CONSTRAINT PK_BKPF PRIMARY KEY (MANDT, BUKRS, BELNR, GJAHR)
);

-- BSEG: Accounting Document Line Item
CREATE OR REPLACE TABLE SAP.SAP_ECC.BSEG (
    MANDT VARCHAR(3) DEFAULT '800',
    BUKRS VARCHAR(4) NOT NULL,
    BELNR VARCHAR(10) NOT NULL,
    GJAHR VARCHAR(4) NOT NULL,
    BUZEI VARCHAR(3) NOT NULL,
    KOART VARCHAR(1),
    SHKZG VARCHAR(1),
    DMBTR NUMBER(13,2),
    WRBTR NUMBER(13,2),
    HKONT VARCHAR(10),
    KOSTL VARCHAR(10),
    MATNR VARCHAR(18),
    CONSTRAINT PK_BSEG PRIMARY KEY (MANDT, BUKRS, BELNR, GJAHR, BUZEI),
    CONSTRAINT FK_BSEG_BKPF FOREIGN KEY (MANDT, BUKRS, BELNR, GJAHR) REFERENCES SAP.SAP_ECC.BKPF (MANDT, BUKRS, BELNR, GJAHR)
);

-- ============================================================================
-- GENERATE MASTER DATA
-- ============================================================================

-- Plants (5 plants)
INSERT INTO SAP.SAP_ECC.T001W (MANDT, WERKS, NAME1, BUKRS, LAND1)
SELECT '800', WERKS, NAME1, '1000', LAND1
FROM (VALUES
    ('1000', 'Hoofdfabriek Amsterdam', 'NL'),
    ('2000', 'Distributiecentrum Rotterdam', 'NL'),
    ('3000', 'Productie Duitsland', 'DE'),
    ('4000', 'Logistiek Belgie', 'BE'),
    ('5000', 'Warehouse UK', 'GB')
) AS t(WERKS, NAME1, LAND1);

-- Customers (1000 customers)
INSERT INTO SAP.SAP_ECC.KNA1 (MANDT, KUNNR, NAME1, LAND1, ORT01, PSTLZ, STRAS)
SELECT 
    '800',
    LPAD(SEQ4()::VARCHAR, 10, '0'),
    'Klant ' || SEQ4()::VARCHAR || ' ' || 
        CASE MOD(SEQ4(), 10) 
            WHEN 0 THEN 'BV' WHEN 1 THEN 'NV' WHEN 2 THEN 'GmbH' 
            WHEN 3 THEN 'AG' WHEN 4 THEN 'Ltd' WHEN 5 THEN 'SA'
            WHEN 6 THEN 'SRL' WHEN 7 THEN 'Inc' WHEN 8 THEN 'Corp' ELSE 'BVBA'
        END,
    CASE MOD(SEQ4(), 5) 
        WHEN 0 THEN 'NL' WHEN 1 THEN 'DE' WHEN 2 THEN 'BE' WHEN 3 THEN 'GB' ELSE 'FR'
    END,
    CASE MOD(SEQ4(), 10) 
        WHEN 0 THEN 'Amsterdam' WHEN 1 THEN 'Berlin' WHEN 2 THEN 'Brussel'
        WHEN 3 THEN 'London' WHEN 4 THEN 'Paris' WHEN 5 THEN 'Rotterdam'
        WHEN 6 THEN 'Hamburg' WHEN 7 THEN 'Antwerpen' WHEN 8 THEN 'Manchester' ELSE 'Lyon'
    END,
    LPAD((MOD(SEQ4(), 9000) + 1000)::VARCHAR, 5, '0'),
    'Straat ' || (MOD(SEQ4(), 200) + 1)::VARCHAR
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

-- Customer Sales Data (KNVV)
INSERT INTO SAP.SAP_ECC.KNVV (MANDT, KUNNR, VKORG, VTWEG, SPART, KDGRP, WAERS)
SELECT 
    '800',
    LPAD(SEQ4()::VARCHAR, 10, '0'),
    '1000',
    '10',
    '00',
    LPAD((MOD(SEQ4(), 5) + 1)::VARCHAR, 2, '0'),
    CASE MOD(SEQ4(), 3) WHEN 0 THEN 'EUR' WHEN 1 THEN 'GBP' ELSE 'USD' END
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

-- Vendors (200 vendors)
INSERT INTO SAP.SAP_ECC.LFA1 (MANDT, LIFNR, NAME1, LAND1, ORT01, PSTLZ)
SELECT 
    '800',
    LPAD(SEQ4()::VARCHAR, 10, '0'),
    'Leverancier ' || SEQ4()::VARCHAR || ' ' ||
        CASE MOD(SEQ4(), 5) 
            WHEN 0 THEN 'GmbH' WHEN 1 THEN 'BV' WHEN 2 THEN 'Ltd' WHEN 3 THEN 'SA' ELSE 'AG'
        END,
    CASE MOD(SEQ4(), 4) WHEN 0 THEN 'DE' WHEN 1 THEN 'NL' WHEN 2 THEN 'CN' ELSE 'US' END,
    CASE MOD(SEQ4(), 8) 
        WHEN 0 THEN 'Frankfurt' WHEN 1 THEN 'Eindhoven' WHEN 2 THEN 'Shanghai'
        WHEN 3 THEN 'New York' WHEN 4 THEN 'Munich' WHEN 5 THEN 'Utrecht'
        WHEN 6 THEN 'Shenzhen' ELSE 'Chicago'
    END,
    LPAD((MOD(SEQ4(), 9000) + 1000)::VARCHAR, 5, '0')
FROM TABLE(GENERATOR(ROWCOUNT => 200));

-- Materials (500 materials)
INSERT INTO SAP.SAP_ECC.MARA (MANDT, MATNR, MTART, MBRSH, MATKL, MEINS, BRGEW, GEWEI, ERDAT)
SELECT 
    '800',
    LPAD(SEQ4()::VARCHAR, 18, '0'),
    CASE MOD(SEQ4(), 4) WHEN 0 THEN 'FERT' WHEN 1 THEN 'HALB' WHEN 2 THEN 'ROH' ELSE 'HAWA' END,
    CASE MOD(SEQ4(), 3) WHEN 0 THEN 'M' WHEN 1 THEN 'E' ELSE 'C' END,
    LPAD((MOD(SEQ4(), 20) + 1)::VARCHAR, 9, '0'),
    CASE MOD(SEQ4(), 3) WHEN 0 THEN 'ST' WHEN 1 THEN 'KG' ELSE 'L' END,
    ROUND(UNIFORM(0.1, 50.0, RANDOM()), 3),
    'KG',
    DATEADD(DAY, -UNIFORM(100, 3000, RANDOM()), CURRENT_DATE())
FROM TABLE(GENERATOR(ROWCOUNT => 500));

-- Material Descriptions
INSERT INTO SAP.SAP_ECC.MAKT (MANDT, MATNR, SPRAS, MAKTX)
SELECT 
    '800',
    LPAD(SEQ4()::VARCHAR, 18, '0'),
    'E',
    CASE MOD(SEQ4(), 20)
        WHEN 0 THEN 'Hydraulic Pump Assembly'
        WHEN 1 THEN 'Steel Plate 10mm'
        WHEN 2 THEN 'Electronic Controller'
        WHEN 3 THEN 'Bearing Set Industrial'
        WHEN 4 THEN 'Copper Wire 2.5mm'
        WHEN 5 THEN 'Plastic Housing Unit'
        WHEN 6 THEN 'Aluminium Profile'
        WHEN 7 THEN 'Gear Box Standard'
        WHEN 8 THEN 'Sensor Module Type A'
        WHEN 9 THEN 'Rubber Seal Kit'
        WHEN 10 THEN 'Stainless Steel Bolt M12'
        WHEN 11 THEN 'Circuit Board PCB-X'
        WHEN 12 THEN 'Filter Element HF-200'
        WHEN 13 THEN 'Motor 3-Phase 5kW'
        WHEN 14 THEN 'Cable Assembly 5m'
        WHEN 15 THEN 'Paint RAL 9010 White'
        WHEN 16 THEN 'Valve DN50 PN16'
        WHEN 17 THEN 'Transformer 230V/24V'
        WHEN 18 THEN 'Packaging Box 400x300'
        ELSE 'Lubricant Industrial Grade'
    END || ' Var-' || LPAD(SEQ4()::VARCHAR, 3, '0')
FROM TABLE(GENERATOR(ROWCOUNT => 500));

-- Material Plant Data (MARC) - each material in 2-3 plants
INSERT INTO SAP.SAP_ECC.MARC (MANDT, MATNR, WERKS, DISMM, DISPO, BESKZ, SOBSL)
SELECT DISTINCT '800', m.MATNR, p.WERKS,
    CASE MOD(ABS(HASH(m.MATNR || p.WERKS)), 3) WHEN 0 THEN 'PD' WHEN 1 THEN 'VB' ELSE 'ND' END,
    LPAD((MOD(ABS(HASH(m.MATNR)), 10) + 1)::VARCHAR, 3, '0'),
    CASE MOD(ABS(HASH(m.MATNR || p.WERKS)), 2) WHEN 0 THEN 'E' ELSE 'F' END,
    ''
FROM SAP.SAP_ECC.MARA m
CROSS JOIN SAP.SAP_ECC.T001W p
WHERE MOD(ABS(HASH(m.MATNR || p.WERKS)), 3) < 2;

-- Storage Location Stocks (MARD)
INSERT INTO SAP.SAP_ECC.MARD (MANDT, MATNR, WERKS, LGORT, LABST, INSME, SPEME)
SELECT '800', mc.MATNR, mc.WERKS, '0001',
    ROUND(UNIFORM(0, 5000, RANDOM()), 0),
    ROUND(UNIFORM(0, 100, RANDOM()), 0),
    ROUND(UNIFORM(0, 50, RANDOM()), 0)
FROM SAP.SAP_ECC.MARC mc;

-- ============================================================================
-- GENERATE 100,000 SALES ORDERS (VBAK) + ITEMS
-- ============================================================================

-- Sales Order Headers (100,000 orders)
INSERT INTO SAP.SAP_ECC.VBAK (MANDT, VBELN, AUART, VKORG, VTWEG, SPART, KUNNR, ERDAT, NETWR, WAERK)
SELECT 
    '800',
    LPAD((SEQ4() + 1)::VARCHAR, 10, '0'),
    CASE MOD(SEQ4(), 6) 
        WHEN 0 THEN 'TA' WHEN 1 THEN 'TA' WHEN 2 THEN 'TA' 
        WHEN 3 THEN 'SO' WHEN 4 THEN 'RE' ELSE 'KE'
    END,
    '1000',
    '10',
    '00',
    LPAD((MOD(SEQ4(), 1000))::VARCHAR, 10, '0'),
    DATEADD(DAY, -UNIFORM(0, 730, RANDOM()), CURRENT_DATE()),
    ROUND(UNIFORM(100, 50000, RANDOM()), 2),
    'EUR'
FROM TABLE(GENERATOR(ROWCOUNT => 100000));

-- Sales Order Items (avg 2.5 items per order = ~250,000 items)
INSERT INTO SAP.SAP_ECC.VBAP (MANDT, VBELN, POSNR, MATNR, KWMENG, VRKME, NETWR, WERKS)
SELECT 
    '800',
    LPAD(ORD_NUM::VARCHAR, 10, '0'),
    LPAD((ITEM_NUM * 10)::VARCHAR, 6, '0'),
    LPAD((MOD(ABS(HASH(ORD_NUM::VARCHAR || ITEM_NUM::VARCHAR)), 500))::VARCHAR, 18, '0'),
    ROUND(UNIFORM(1, 100, RANDOM()), 0),
    'ST',
    ROUND(UNIFORM(50, 20000, RANDOM()), 2),
    CASE MOD(ABS(HASH(ORD_NUM::VARCHAR)), 5)
        WHEN 0 THEN '1000' WHEN 1 THEN '2000' WHEN 2 THEN '3000' WHEN 3 THEN '4000' ELSE '5000'
    END
FROM (
    SELECT o.SEQ AS ORD_NUM, i.SEQ AS ITEM_NUM
    FROM (SELECT SEQ4() + 1 AS SEQ FROM TABLE(GENERATOR(ROWCOUNT => 100000))) o
    CROSS JOIN (SELECT SEQ4() + 1 AS SEQ FROM TABLE(GENERATOR(ROWCOUNT => 5))) i
    WHERE i.SEQ <= GREATEST(1, MOD(ABS(HASH(o.SEQ::VARCHAR)), 5) + 1)
);

-- Schedule Lines (VBEP) - 1 per item
INSERT INTO SAP.SAP_ECC.VBEP (MANDT, VBELN, POSNR, ETENR, EDATU, WMENG, VRKME)
SELECT MANDT, VBELN, POSNR, '0001', 
    DATEADD(DAY, UNIFORM(5, 30, RANDOM()), CURRENT_DATE()),
    KWMENG, VRKME
FROM SAP.SAP_ECC.VBAP;

-- Sales Order Business Data (VBKD) - header level
INSERT INTO SAP.SAP_ECC.VBKD (MANDT, VBELN, POSNR, ZTERM, INCO1, INCO2)
SELECT DISTINCT MANDT, VBELN, '000000',
    CASE MOD(ABS(HASH(VBELN)), 5)
        WHEN 0 THEN 'Z030' WHEN 1 THEN 'Z060' WHEN 2 THEN 'Z014' WHEN 3 THEN 'Z090' ELSE 'Z045'
    END,
    CASE MOD(ABS(HASH(VBELN)), 4)
        WHEN 0 THEN 'EXW' WHEN 1 THEN 'FCA' WHEN 2 THEN 'CIF' ELSE 'DDP'
    END,
    CASE MOD(ABS(HASH(VBELN)), 4)
        WHEN 0 THEN 'Amsterdam' WHEN 1 THEN 'Rotterdam' WHEN 2 THEN 'Hamburg' ELSE 'Antwerpen'
    END
FROM SAP.SAP_ECC.VBAK;

-- Partners (VBPA) - sold-to (AG) and ship-to (WE)
INSERT INTO SAP.SAP_ECC.VBPA (MANDT, VBELN, POSNR, PARVW, KUNNR, LIFNR)
SELECT MANDT, VBELN, '000000', 'AG', KUNNR, NULL FROM SAP.SAP_ECC.VBAK
UNION ALL
SELECT MANDT, VBELN, '000000', 'WE', KUNNR, NULL FROM SAP.SAP_ECC.VBAK
UNION ALL
SELECT MANDT, VBELN, '000000', 'RE', KUNNR, NULL FROM SAP.SAP_ECC.VBAK;

-- Order Header Status (VBUK)
INSERT INTO SAP.SAP_ECC.VBUK (MANDT, VBELN, GBSTK, LFSTK)
SELECT MANDT, VBELN, 
    CASE WHEN ERDAT < DATEADD(DAY, -60, CURRENT_DATE()) THEN 'C'
         WHEN ERDAT < DATEADD(DAY, -14, CURRENT_DATE()) THEN 'B'
         ELSE 'A' END,
    CASE WHEN ERDAT < DATEADD(DAY, -45, CURRENT_DATE()) THEN 'C'
         WHEN ERDAT < DATEADD(DAY, -7, CURRENT_DATE()) THEN 'B'
         ELSE 'A' END
FROM SAP.SAP_ECC.VBAK;

-- Order Item Status (VBUP)
INSERT INTO SAP.SAP_ECC.VBUP (MANDT, VBELN, POSNR, GBSTA, LFSTA)
SELECT v.MANDT, v.VBELN, v.POSNR,
    u.GBSTK, u.LFSTK
FROM SAP.SAP_ECC.VBAP v
JOIN SAP.SAP_ECC.VBUK u ON v.MANDT = u.MANDT AND v.VBELN = u.VBELN;

-- ============================================================================
-- GENERATE DELIVERIES (80% of completed orders)
-- ============================================================================

-- Delivery Headers (LIKP)
INSERT INTO SAP.SAP_ECC.LIKP (MANDT, VBELN, LFART, KUNNR, WADAT)
SELECT '800',
    LPAD((ROW_NUMBER() OVER (ORDER BY v.VBELN) + 8000000)::VARCHAR, 10, '0'),
    'LF',
    v.KUNNR,
    DATEADD(DAY, UNIFORM(2, 10, RANDOM()), v.ERDAT)
FROM SAP.SAP_ECC.VBAK v
JOIN SAP.SAP_ECC.VBUK u ON v.MANDT = u.MANDT AND v.VBELN = u.VBELN
WHERE u.LFSTK IN ('B', 'C');

-- Delivery Items (LIPS)
INSERT INTO SAP.SAP_ECC.LIPS (MANDT, VBELN, POSNR, MATNR, LFIMG, VRKME, WERKS)
SELECT l.MANDT, l.VBELN, ap.POSNR, ap.MATNR, ap.KWMENG, ap.VRKME, ap.WERKS
FROM SAP.SAP_ECC.LIKP l
JOIN SAP.SAP_ECC.VBAK ak ON l.KUNNR = ak.KUNNR AND l.MANDT = ak.MANDT
    AND ak.ERDAT = DATEADD(DAY, -UNIFORM(2, 10, RANDOM()), l.WADAT)
JOIN SAP.SAP_ECC.VBAP ap ON ak.MANDT = ap.MANDT AND ak.VBELN = ap.VBELN
WHERE 1=0; -- placeholder, fill below with correct logic

-- Correct LIPS generation: link delivery items to order items via VBFA flow
TRUNCATE TABLE SAP.SAP_ECC.LIPS;
INSERT INTO SAP.SAP_ECC.LIPS (MANDT, VBELN, POSNR, MATNR, LFIMG, VRKME, WERKS)
WITH delivery_orders AS (
    SELECT l.VBELN AS DEL_VBELN, l.MANDT, l.KUNNR,
           ROW_NUMBER() OVER (ORDER BY l.VBELN) as RN
    FROM SAP.SAP_ECC.LIKP l
),
source_orders AS (
    SELECT v.VBELN AS ORD_VBELN, v.MANDT, v.KUNNR,
           ROW_NUMBER() OVER (PARTITION BY v.KUNNR ORDER BY v.ERDAT) as RN
    FROM SAP.SAP_ECC.VBAK v
    JOIN SAP.SAP_ECC.VBUK u ON v.MANDT = u.MANDT AND v.VBELN = u.VBELN
    WHERE u.LFSTK IN ('B', 'C')
)
SELECT d.MANDT, d.DEL_VBELN, ap.POSNR, ap.MATNR, ap.KWMENG, ap.VRKME, ap.WERKS
FROM delivery_orders d
JOIN source_orders s ON d.MANDT = s.MANDT AND d.KUNNR = s.KUNNR AND d.RN = s.RN
JOIN SAP.SAP_ECC.VBAP ap ON s.MANDT = ap.MANDT AND s.ORD_VBELN = ap.VBELN;

-- ============================================================================
-- GENERATE BILLING DOCUMENTS (invoices for delivered orders)
-- ============================================================================

-- Billing Headers (VBRK)
INSERT INTO SAP.SAP_ECC.VBRK (MANDT, VBELN, FKART, KUNNR, FKDAT, NETWR, WAERK)
SELECT l.MANDT,
    LPAD((ROW_NUMBER() OVER (ORDER BY l.VBELN) + 9000000)::VARCHAR, 10, '0'),
    'F2',
    l.KUNNR,
    DATEADD(DAY, UNIFORM(1, 5, RANDOM()), l.WADAT),
    0, -- will be updated from items
    'EUR'
FROM SAP.SAP_ECC.LIKP l
WHERE l.WADAT < DATEADD(DAY, -5, CURRENT_DATE());

-- Billing Items (VBRP)
INSERT INTO SAP.SAP_ECC.VBRP (MANDT, VBELN, POSNR, MATNR, FKIMG, VRKME, NETWR)
SELECT b.MANDT, b.VBELN, li.POSNR, li.MATNR, li.LFIMG, li.VRKME,
    ROUND(li.LFIMG * UNIFORM(10, 500, RANDOM()), 2)
FROM SAP.SAP_ECC.VBRK b
JOIN SAP.SAP_ECC.LIKP l ON b.MANDT = l.MANDT AND b.KUNNR = l.KUNNR
    AND b.FKDAT >= l.WADAT
    AND b.FKDAT <= DATEADD(DAY, 5, l.WADAT)
JOIN SAP.SAP_ECC.LIPS li ON l.MANDT = li.MANDT AND l.VBELN = li.VBELN
QUALIFY ROW_NUMBER() OVER (PARTITION BY b.VBELN, li.POSNR ORDER BY l.VBELN) = 1;

-- Update billing header totals
UPDATE SAP.SAP_ECC.VBRK b
SET NETWR = (SELECT COALESCE(SUM(p.NETWR), 0) FROM SAP.SAP_ECC.VBRP p WHERE p.MANDT = b.MANDT AND p.VBELN = b.VBELN);

-- ============================================================================
-- DOCUMENT FLOW (VBFA) - links orders -> deliveries -> invoices
-- ============================================================================

-- Order to Delivery flow
INSERT INTO SAP.SAP_ECC.VBFA (MANDT, VBELV, POSNV, VBELN, POSNN, VBTYP_N, ERDAT)
WITH order_del_map AS (
    SELECT d.MANDT, s.ORD_VBELN, d.DEL_VBELN, d.RN
    FROM (
        SELECT l.VBELN AS DEL_VBELN, l.MANDT, l.KUNNR, l.WADAT,
               ROW_NUMBER() OVER (ORDER BY l.VBELN) as RN
        FROM SAP.SAP_ECC.LIKP l
    ) d
    JOIN (
        SELECT v.VBELN AS ORD_VBELN, v.MANDT, v.KUNNR,
               ROW_NUMBER() OVER (PARTITION BY v.KUNNR ORDER BY v.ERDAT) as RN
        FROM SAP.SAP_ECC.VBAK v
        JOIN SAP.SAP_ECC.VBUK u ON v.MANDT = u.MANDT AND v.VBELN = u.VBELN
        WHERE u.LFSTK IN ('B', 'C')
    ) s ON d.MANDT = s.MANDT AND d.KUNNR = s.KUNNR AND d.RN = s.RN
)
SELECT m.MANDT, m.ORD_VBELN, '000010', m.DEL_VBELN, '000010', 'J', CURRENT_DATE()
FROM order_del_map m
LIMIT 100000;

-- ============================================================================
-- PRICING CONDITIONS (KONV)
-- ============================================================================

INSERT INTO SAP.SAP_ECC.KONV (MANDT, KNUMV, KPOSN, STUNR, ZAEHK, KSCHL, KBETR, WAERS, KWERT)
SELECT 
    ap.MANDT,
    ap.VBELN,  -- condition number = order number
    ap.POSNR,
    '010', '01',
    'PR00',  -- base price
    ROUND(ap.NETWR / GREATEST(ap.KWMENG, 1), 2),
    'EUR',
    ap.NETWR
FROM SAP.SAP_ECC.VBAP ap
WHERE MOD(ABS(HASH(ap.VBELN || ap.POSNR)), 1) = 0  -- all items get base price
LIMIT 250000;

-- Discount conditions for ~30% of items
INSERT INTO SAP.SAP_ECC.KONV (MANDT, KNUMV, KPOSN, STUNR, ZAEHK, KSCHL, KBETR, WAERS, KWERT)
SELECT 
    ap.MANDT,
    ap.VBELN,
    ap.POSNR,
    '020', '01',
    'K004',  -- discount
    -ROUND(UNIFORM(2, 15, RANDOM()), 2),
    'EUR',
    -ROUND(ap.NETWR * UNIFORM(0.02, 0.15, RANDOM()), 2)
FROM SAP.SAP_ECC.VBAP ap
WHERE MOD(ABS(HASH(ap.VBELN || ap.POSNR)), 3) = 0
LIMIT 80000;

-- ============================================================================
-- PURCHASE ORDERS (linked to materials)
-- ============================================================================

-- PO Headers (20,000 POs)
INSERT INTO SAP.SAP_ECC.EKKO (MANDT, EBELN, BUKRS, BSTYP, BSART, LIFNR, EKORG, BEDAT, WAERS)
SELECT 
    '800',
    LPAD((SEQ4() + 4500000)::VARCHAR, 10, '0'),
    '1000',
    'F',
    CASE MOD(SEQ4(), 3) WHEN 0 THEN 'NB' WHEN 1 THEN 'NB' ELSE 'UB' END,
    LPAD((MOD(SEQ4(), 200))::VARCHAR, 10, '0'),
    '1000',
    DATEADD(DAY, -UNIFORM(0, 730, RANDOM()), CURRENT_DATE()),
    'EUR'
FROM TABLE(GENERATOR(ROWCOUNT => 20000));

-- PO Items (avg 3 per PO = ~60,000)
INSERT INTO SAP.SAP_ECC.EKPO (MANDT, EBELN, EBELP, MATNR, MENGE, MEINS, NETPR, WERKS, LIFNR)
SELECT 
    '800',
    LPAD((ORD_NUM + 4500000)::VARCHAR, 10, '0'),
    LPAD((ITEM_NUM * 10)::VARCHAR, 5, '0'),
    LPAD((MOD(ABS(HASH(ORD_NUM::VARCHAR || ITEM_NUM::VARCHAR)), 500))::VARCHAR, 18, '0'),
    ROUND(UNIFORM(10, 1000, RANDOM()), 0),
    'ST',
    ROUND(UNIFORM(5, 500, RANDOM()), 2),
    CASE MOD(ABS(HASH(ORD_NUM::VARCHAR)), 5)
        WHEN 0 THEN '1000' WHEN 1 THEN '2000' WHEN 2 THEN '3000' WHEN 3 THEN '4000' ELSE '5000'
    END,
    LPAD((MOD(ORD_NUM, 200))::VARCHAR, 10, '0')
FROM (
    SELECT o.SEQ AS ORD_NUM, i.SEQ AS ITEM_NUM
    FROM (SELECT SEQ4() AS SEQ FROM TABLE(GENERATOR(ROWCOUNT => 20000))) o
    CROSS JOIN (SELECT SEQ4() + 1 AS SEQ FROM TABLE(GENERATOR(ROWCOUNT => 5))) i
    WHERE i.SEQ <= GREATEST(1, MOD(ABS(HASH(o.SEQ::VARCHAR)), 4) + 1)
);

-- ============================================================================
-- ACCOUNTING DOCUMENTS (FI) - linked to billing
-- ============================================================================

-- FI Document Headers (from billing)
INSERT INTO SAP.SAP_ECC.BKPF (MANDT, BUKRS, BELNR, GJAHR, BLART, BUDAT, BLDAT, WAERS, USNAM)
SELECT 
    '800', '1000',
    LPAD((ROW_NUMBER() OVER (ORDER BY VBELN))::VARCHAR, 10, '0'),
    TO_CHAR(FKDAT, 'YYYY'),
    'RV',
    FKDAT,
    FKDAT,
    WAERK,
    'BATCH'
FROM SAP.SAP_ECC.VBRK
LIMIT 50000;

-- FI Document Line Items
INSERT INTO SAP.SAP_ECC.BSEG (MANDT, BUKRS, BELNR, GJAHR, BUZEI, KOART, SHKZG, DMBTR, WRBTR, HKONT, KOSTL, MATNR)
WITH bkpf_numbered AS (
    SELECT b.MANDT, b.BUKRS, b.BELNR, b.GJAHR, b.BUDAT,
           ROW_NUMBER() OVER (ORDER BY b.BELNR) AS RN
    FROM SAP.SAP_ECC.BKPF b
),
vbrk_numbered AS (
    SELECT vk.VBELN, vk.NETWR, vk.FKDAT,
           ROW_NUMBER() OVER (ORDER BY vk.VBELN) AS RN
    FROM SAP.SAP_ECC.VBRK vk
)
SELECT 
    bn.MANDT, bn.BUKRS, bn.BELNR, bn.GJAHR,
    '001', 'D', 'S', 
    COALESCE(vn.NETWR, 1000), COALESCE(vn.NETWR, 1000),
    '0000140000', '', ''
FROM bkpf_numbered bn
LEFT JOIN vbrk_numbered vn ON bn.RN = vn.RN
QUALIFY ROW_NUMBER() OVER (PARTITION BY bn.BUKRS, bn.BELNR, bn.GJAHR ORDER BY bn.BELNR) = 1;

-- Revenue line
INSERT INTO SAP.SAP_ECC.BSEG (MANDT, BUKRS, BELNR, GJAHR, BUZEI, KOART, SHKZG, DMBTR, WRBTR, HKONT, KOSTL, MATNR)
SELECT 
    MANDT, BUKRS, BELNR, GJAHR,
    '002', 'S', 'H', DMBTR, WRBTR, '0000800000', '1000', ''
FROM SAP.SAP_ECC.BSEG
WHERE BUZEI = '001';

-- ============================================================================
-- VERIFICATION
-- ============================================================================
SELECT 'T001W' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM SAP.SAP_ECC.T001W
UNION ALL SELECT 'KNA1', COUNT(*) FROM SAP.SAP_ECC.KNA1
UNION ALL SELECT 'LFA1', COUNT(*) FROM SAP.SAP_ECC.LFA1
UNION ALL SELECT 'MARA', COUNT(*) FROM SAP.SAP_ECC.MARA
UNION ALL SELECT 'MAKT', COUNT(*) FROM SAP.SAP_ECC.MAKT
UNION ALL SELECT 'MARC', COUNT(*) FROM SAP.SAP_ECC.MARC
UNION ALL SELECT 'MARD', COUNT(*) FROM SAP.SAP_ECC.MARD
UNION ALL SELECT 'VBAK', COUNT(*) FROM SAP.SAP_ECC.VBAK
UNION ALL SELECT 'VBAP', COUNT(*) FROM SAP.SAP_ECC.VBAP
UNION ALL SELECT 'VBEP', COUNT(*) FROM SAP.SAP_ECC.VBEP
UNION ALL SELECT 'VBKD', COUNT(*) FROM SAP.SAP_ECC.VBKD
UNION ALL SELECT 'VBPA', COUNT(*) FROM SAP.SAP_ECC.VBPA
UNION ALL SELECT 'VBUK', COUNT(*) FROM SAP.SAP_ECC.VBUK
UNION ALL SELECT 'VBUP', COUNT(*) FROM SAP.SAP_ECC.VBUP
UNION ALL SELECT 'VBFA', COUNT(*) FROM SAP.SAP_ECC.VBFA
UNION ALL SELECT 'KONV', COUNT(*) FROM SAP.SAP_ECC.KONV
UNION ALL SELECT 'LIKP', COUNT(*) FROM SAP.SAP_ECC.LIKP
UNION ALL SELECT 'LIPS', COUNT(*) FROM SAP.SAP_ECC.LIPS
UNION ALL SELECT 'VBRK', COUNT(*) FROM SAP.SAP_ECC.VBRK
UNION ALL SELECT 'VBRP', COUNT(*) FROM SAP.SAP_ECC.VBRP
UNION ALL SELECT 'EKKO', COUNT(*) FROM SAP.SAP_ECC.EKKO
UNION ALL SELECT 'EKPO', COUNT(*) FROM SAP.SAP_ECC.EKPO
UNION ALL SELECT 'BKPF', COUNT(*) FROM SAP.SAP_ECC.BKPF
UNION ALL SELECT 'BSEG', COUNT(*) FROM SAP.SAP_ECC.BSEG
UNION ALL SELECT 'KNVV', COUNT(*) FROM SAP.SAP_ECC.KNVV
ORDER BY TABLE_NAME;
