-- SAP ECC Table Creation and Data Loading Script
-- Generated from sap/dd/DD03L.csv definitions
-- Data uses SAP DATS format: YYYYMMDD

-- Step 1: Create database and schema
CREATE DATABASE IF NOT EXISTS SAP;
CREATE SCHEMA IF NOT EXISTS SAP.BRONZE;
CREATE SCHEMA IF NOT EXISTS SAP.SILVER;
CREATE SCHEMA IF NOT EXISTS SAP.GOLD;
CREATE SCHEMA IF NOT EXISTS SAP.SAP_ECC;
USE SCHEMA SAP.SAP_ECC;

-- Step 2: Create file format for CSV loading
CREATE OR REPLACE FILE FORMAT SAP.SAP_ECC.SAP_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'YYYYMMDD'
    TIME_FORMAT = 'HH24MISS';

-- Step 3: Create internal stage and copy CSV files from workspace
CREATE OR REPLACE STAGE SAP.SAP_ECC.SAP_DATA_STAGE
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT;

COPY FILES INTO @SAP.SAP_ECC.SAP_DATA_STAGE
    FROM 'snow://workspace/USER$.PUBLIC."sap-demo"/versions/live/sap/data/'
    PATTERN = '.*[.]csv';

-- Step 4: Create tables and load data
CREATE OR REPLACE TABLE SAP.SAP_ECC.AFKO (
    MANDT VARCHAR(3),
    AUFNR VARCHAR(12),
    DESSION VARCHAR(8),
    STLNR VARCHAR(8),
    GAMNG NUMBER(13,3),
    GMEIN VARCHAR(3),
    GLTRS DATE,
    GLTRP DATE
);
COPY INTO SAP.SAP_ECC.AFKO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/AFKO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.AFPO (
    MANDT VARCHAR(3),
    AUFNR VARCHAR(12),
    POSNR VARCHAR(4),
    MATNR VARCHAR(18),
    PSMNG NUMBER(13,3),
    MEINS VARCHAR(3),
    WERKS VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.AFPO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/AFPO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.AFVC (
    MANDT VARCHAR(3),
    AUFPL VARCHAR(10),
    APLZL VARCHAR(8),
    VORNR VARCHAR(4),
    ARBID VARCHAR(8),
    WERKS VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.AFVC
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/AFVC.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.AFVV (
    MANDT VARCHAR(3),
    AUFPL VARCHAR(10),
    APLZL VARCHAR(8),
    MGVRG NUMBER(13,3),
    MEINH VARCHAR(3),
    DAESSION VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.AFVV
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/AFVV.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.AGR_TEXTS (
    MANDT VARCHAR(3),
    AGR_NAME VARCHAR(30),
    SPRAS VARCHAR(1),
    LINE VARCHAR(3),
    TEXT VARCHAR(80)
);
COPY INTO SAP.SAP_ECC.AGR_TEXTS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/AGR_TEXTS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.AGR_USERS (
    MANDT VARCHAR(3),
    AGR_NAME VARCHAR(30),
    UNAME VARCHAR(12),
    FROM_DAT DATE,
    TO_DAT DATE
);
COPY INTO SAP.SAP_ECC.AGR_USERS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/AGR_USERS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.ANEP (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    ANLN1 VARCHAR(12),
    ANLN2 VARCHAR(4),
    GJAHR VARCHAR(4),
    LNRAN VARCHAR(3),
    AFABE VARCHAR(2),
    BWASL VARCHAR(3),
    ANBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.ANEP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/ANEP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.ANLA (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    ANLN1 VARCHAR(12),
    ANLN2 VARCHAR(4),
    ANLKL VARCHAR(8),
    TXT50 VARCHAR(50),
    AKTIV DATE,
    DEAKT DATE,
    KOSTL VARCHAR(10),
    WERKS VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.ANLA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/ANLA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.AUFK (
    MANDT VARCHAR(3),
    AUFNR VARCHAR(12),
    AUTYP VARCHAR(2),
    BUKRS VARCHAR(4),
    WERKS VARCHAR(4),
    KOSTL VARCHAR(10),
    ERDAT DATE,
    ERNAM VARCHAR(12)
);
COPY INTO SAP.SAP_ECC.AUFK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/AUFK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BALDAT (
    MANDT VARCHAR(3),
    LOG_HANDLE VARCHAR(22),
    LOGNUMBER VARCHAR(6),
    MSG_DATA VARCHAR(200)
);
COPY INTO SAP.SAP_ECC.BALDAT
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BALDAT.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BALHDR (
    MANDT VARCHAR(3),
    LOG_HANDLE VARCHAR(22),
    OBJECT VARCHAR(20),
    SUBOBJECT VARCHAR(20),
    ALDATE DATE,
    ALTIME TIME,
    ALUSER VARCHAR(12)
);
COPY INTO SAP.SAP_ECC.BALHDR
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BALHDR.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BDCP2 (
    MANDT VARCHAR(3),
    MESTYP VARCHAR(30),
    CPIDENT VARCHAR(26),
    TABNAME VARCHAR(30),
    TABKEY VARCHAR(70),
    CRESSION_DATE DATE
);
COPY INTO SAP.SAP_ECC.BDCP2
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BDCP2.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BKPF (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    BELNR VARCHAR(10),
    GJAHR VARCHAR(4),
    BLART VARCHAR(2),
    BUDAT DATE,
    BLDAT DATE,
    WAERS VARCHAR(5),
    USNAM VARCHAR(12)
);
COPY INTO SAP.SAP_ECC.BKPF
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BKPF.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSAD (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    KUNNR VARCHAR(10),
    UMSKS VARCHAR(1),
    AUGDT DATE,
    AUGBL VARCHAR(10),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.BSAD
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BSAD.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSAK (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    LIFNR VARCHAR(10),
    UMSKS VARCHAR(1),
    AUGDT DATE,
    AUGBL VARCHAR(10),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.BSAK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BSAK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSAS (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    HKONT VARCHAR(10),
    AUGDT DATE,
    AUGBL VARCHAR(10),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.BSAS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BSAS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSEG (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    BELNR VARCHAR(10),
    GJAHR VARCHAR(4),
    BUZEI VARCHAR(3),
    KOART VARCHAR(1),
    SHKZG VARCHAR(1),
    DMBTR NUMBER(13,2),
    WRBTR NUMBER(13,2),
    HKONT VARCHAR(10),
    KOSTL VARCHAR(10),
    MATNR VARCHAR(18)
);
COPY INTO SAP.SAP_ECC.BSEG
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BSEG.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSID (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    KUNNR VARCHAR(10),
    UMSKS VARCHAR(1),
    BUDAT DATE,
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.BSID
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BSID.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSIK (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    LIFNR VARCHAR(10),
    UMSKS VARCHAR(1),
    BUDAT DATE,
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.BSIK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/BSIK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CDHDR (
    MANDT VARCHAR(3),
    OBJECTCLAS VARCHAR(15),
    OBJECTID VARCHAR(90),
    CHANGENR VARCHAR(10),
    USERNAME VARCHAR(12),
    UDATE DATE,
    UTIME TIME,
    TCODE VARCHAR(20)
);
COPY INTO SAP.SAP_ECC.CDHDR
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CDHDR.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CDPOS (
    MANDT VARCHAR(3),
    OBJECTCLAS VARCHAR(15),
    OBJECTID VARCHAR(90),
    CHANGENR VARCHAR(10),
    TABNAME VARCHAR(30),
    TABKEY VARCHAR(70),
    FNAME VARCHAR(30),
    CHNGIND VARCHAR(1),
    VALUE_NEW VARCHAR(254),
    VALUE_OLD VARCHAR(254)
);
COPY INTO SAP.SAP_ECC.CDPOS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CDPOS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CE1XXXX (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    PESSION VARCHAR(10),
    KUNNR VARCHAR(10),
    MATNR VARCHAR(18),
    VKORG VARCHAR(4),
    WERKS VARCHAR(4),
    PERDE VARCHAR(3),
    GJAHR VARCHAR(4),
    VV010 NUMBER(13,2),
    TWAER VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.CE1XXXX
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CE1XXXX.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CE2XXXX (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    PESSION VARCHAR(10),
    KUNNR VARCHAR(10),
    MATNR VARCHAR(18),
    VKORG VARCHAR(4),
    WERKS VARCHAR(4),
    PESSION2 VARCHAR(3),
    GJAHR VARCHAR(4),
    VV010 NUMBER(13,2),
    TWAER VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.CE2XXXX
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CE2XXXX.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.COBK (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    BESSION VARCHAR(10),
    GJAHR VARCHAR(4),
    BLDAT DATE,
    BUDAT DATE,
    BLTXT VARCHAR(25)
);
COPY INTO SAP.SAP_ECC.COBK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/COBK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.COEP (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    BELNR VARCHAR(10),
    GJAHR VARCHAR(4),
    BUZEI VARCHAR(3),
    KSTAR VARCHAR(10),
    KOSTL VARCHAR(10),
    WRBTR NUMBER(13,2),
    TWAER VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.COEP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/COEP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.COSP (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    OBJNR VARCHAR(22),
    GJAHR VARCHAR(4),
    KSTAR VARCHAR(10),
    WTG001 NUMBER(13,2),
    TWAER VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.COSP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/COSP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.COSS (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    OBJNR VARCHAR(22),
    GJAHR VARCHAR(4),
    KSTAR VARCHAR(10),
    WTG001 NUMBER(13,2),
    TWAER VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.COSS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/COSS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CRHD (
    MANDT VARCHAR(3),
    OBJID VARCHAR(8),
    OBJTY VARCHAR(2),
    WERKS VARCHAR(4),
    ARBPL VARCHAR(8),
    VERWE VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.CRHD
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CRHD.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CRTX (
    MANDT VARCHAR(3),
    OBJID VARCHAR(8),
    SPRAS VARCHAR(1),
    KTEXT VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.CRTX
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CRTX.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKA (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KSTAR VARCHAR(10),
    DATBI DATE,
    KATYP VARCHAR(2)
);
COPY INTO SAP.SAP_ECC.CSKA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CSKA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKB (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KSTAR VARCHAR(10),
    DATBI DATE,
    KATYP VARCHAR(2)
);
COPY INTO SAP.SAP_ECC.CSKB
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CSKB.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKS (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KOSTL VARCHAR(10),
    DATBI DATE,
    BUKRS VARCHAR(4),
    KOSAR VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.CSKS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CSKS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKT (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KOSTL VARCHAR(10),
    SPRAS VARCHAR(1),
    DATBI DATE,
    KTEXT VARCHAR(20),
    LTEXT VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.CSKT
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CSKT.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKU (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KSTAR VARCHAR(10),
    SPRAS VARCHAR(1),
    KTEXT VARCHAR(20),
    LTEXT VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.CSKU
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/CSKU.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD02L (
    TABNAME VARCHAR(30),
    AS4LOCAL VARCHAR(1),
    AS4VERS VARCHAR(4),
    TABCLASS VARCHAR(8),
    SQLTAB VARCHAR(30),
    AUTHCLASS VARCHAR(2),
    MASTERLANG VARCHAR(1),
    CONTFLAG VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.DD02L
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD02L.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD03L (
    TABNAME VARCHAR(30),
    FIELDNAME VARCHAR(30),
    AS4LOCAL VARCHAR(1),
    AS4VERS VARCHAR(4),
    POSITION VARCHAR(4),
    KEYFLAG VARCHAR(1),
    DATATYPE VARCHAR(4),
    LENG VARCHAR(6),
    DECIMALS VARCHAR(6),
    DOMNAME VARCHAR(30),
    ROLLNAME VARCHAR(30)
);
COPY INTO SAP.SAP_ECC.DD03L
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD03L.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EBAN (
    MANDT VARCHAR(3),
    BANFN VARCHAR(10),
    BNFPO VARCHAR(5),
    MATNR VARCHAR(18),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    WERKS VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.EBAN
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EBAN.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EDID4 (
    MANDT VARCHAR(3),
    DOCNUM VARCHAR(16),
    COUNTER VARCHAR(6),
    SEGNAM VARCHAR(27),
    SDATA VARCHAR(1000)
);
COPY INTO SAP.SAP_ECC.EDID4
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EDID4.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EDIDC (
    MANDT VARCHAR(3),
    DOCNUM VARCHAR(16),
    MESTYP VARCHAR(30),
    IDOCTP VARCHAR(30),
    STATUS VARCHAR(2),
    CREDAT DATE,
    CRETIM TIME,
    SNDPRT VARCHAR(2),
    SNDPRN VARCHAR(10),
    RCVPRT VARCHAR(2),
    RCVPRN VARCHAR(10)
);
COPY INTO SAP.SAP_ECC.EDIDC
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EDIDC.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EINA (
    MANDT VARCHAR(3),
    INFNR VARCHAR(10),
    MATNR VARCHAR(18),
    LIFNR VARCHAR(10),
    LOEKZ VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.EINA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EINA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EINE (
    MANDT VARCHAR(3),
    INFNR VARCHAR(10),
    EKORG VARCHAR(4),
    WERKS VARCHAR(4),
    NETPR NUMBER(13,2),
    WAERS VARCHAR(5),
    PEINH NUMBER(5,0)
);
COPY INTO SAP.SAP_ECC.EINE
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EINE.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EKBE (
    MANDT VARCHAR(3),
    EBELN VARCHAR(10),
    EBELP VARCHAR(5),
    ZEKKN VARCHAR(5),
    VGABE VARCHAR(1),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    BUZEI VARCHAR(3),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.EKBE
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EKBE.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EKET (
    MANDT VARCHAR(3),
    EBELN VARCHAR(10),
    EBELP VARCHAR(5),
    ETENR VARCHAR(4),
    EINDT DATE,
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    WEMNG NUMBER(13,3)
);
COPY INTO SAP.SAP_ECC.EKET
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EKET.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EKKO (
    MANDT VARCHAR(3),
    EBELN VARCHAR(10),
    BUKRS VARCHAR(4),
    BSTYP VARCHAR(1),
    BSART VARCHAR(4),
    LIFNR VARCHAR(10),
    EKORG VARCHAR(4),
    BEDAT DATE,
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.EKKO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EKKO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.EKPO (
    MANDT VARCHAR(3),
    EBELN VARCHAR(10),
    EBELP VARCHAR(5),
    MATNR VARCHAR(18),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    NETPR NUMBER(13,2),
    WERKS VARCHAR(4),
    LIFNR VARCHAR(10)
);
COPY INTO SAP.SAP_ECC.EKPO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/EKPO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.FAGLFLEXA (
    MANDT VARCHAR(3),
    RLDNR VARCHAR(2),
    BUKRS VARCHAR(4),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DOCLN VARCHAR(6),
    RACCT VARCHAR(10),
    KOSTL VARCHAR(10),
    HSL NUMBER(13,2),
    RHCUR VARCHAR(5),
    BUDAT DATE
);
COPY INTO SAP.SAP_ECC.FAGLFLEXA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/FAGLFLEXA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.HRP1000 (
    MANDT VARCHAR(3),
    PLVAR VARCHAR(2),
    OTYPE VARCHAR(2),
    OBJID VARCHAR(8),
    BEGDA DATE,
    ENDDA DATE,
    STEXT VARCHAR(40),
    LANGU VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.HRP1000
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/HRP1000.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.HRP1001 (
    MANDT VARCHAR(3),
    PLVAR VARCHAR(2),
    OTYPE VARCHAR(2),
    OBJID VARCHAR(8),
    SUBTY VARCHAR(4),
    BEGDA DATE,
    ENDDA DATE,
    SCLAS VARCHAR(2),
    SOBID VARCHAR(8)
);
COPY INTO SAP.SAP_ECC.HRP1001
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/HRP1001.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.HRP1002 (
    MANDT VARCHAR(3),
    PLVAR VARCHAR(2),
    OTYPE VARCHAR(2),
    OBJID VARCHAR(8),
    BEGDA DATE,
    ENDDA DATE,
    DESSION VARCHAR(255)
);
COPY INTO SAP.SAP_ECC.HRP1002
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/HRP1002.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.INFO (
    MANDT VARCHAR(3),
    INFNR VARCHAR(10),
    MATNR VARCHAR(18),
    LIFNR VARCHAR(10),
    LOEKZ VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.INFO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/INFO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.JEST (
    MANDT VARCHAR(3),
    OBJNR VARCHAR(22),
    STAT VARCHAR(5),
    INACT VARCHAR(1),
    CHGNR VARCHAR(6)
);
COPY INTO SAP.SAP_ECC.JEST
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/JEST.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.KEKO (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    KALKA VARCHAR(1),
    KADKY DATE,
    TVERS VARCHAR(2),
    LOSGR NUMBER(13,3),
    MEINS VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.KEKO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/KEKO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.KEPH (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    KALKA VARCHAR(1),
    KADKY DATE,
    TVERS VARCHAR(2),
    ELEHK VARCHAR(2),
    KST001 NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.KEPH
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/KEPH.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.KNA1 (
    MANDT VARCHAR(3),
    KUNNR VARCHAR(10),
    NAME1 VARCHAR(35),
    LAND1 VARCHAR(3),
    ORT01 VARCHAR(35),
    PSTLZ VARCHAR(10),
    STRAS VARCHAR(35)
);
COPY INTO SAP.SAP_ECC.KNA1
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/KNA1.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.KNVV (
    MANDT VARCHAR(3),
    KUNNR VARCHAR(10),
    VKORG VARCHAR(4),
    VTWEG VARCHAR(2),
    SPART VARCHAR(2),
    KDGRP VARCHAR(2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.KNVV
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/KNVV.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.KONV (
    MANDT VARCHAR(3),
    KNUMV VARCHAR(10),
    KPOSN VARCHAR(6),
    STUNR VARCHAR(3),
    ZAESSION VARCHAR(3),
    KSCHL VARCHAR(4),
    KBETR NUMBER(13,2),
    WAERS VARCHAR(5),
    KWERT NUMBER(13,2)
);
COPY INTO SAP.SAP_ECC.KONV
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/KONV.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LAGP (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    LGTYP VARCHAR(3),
    LGPLA VARCHAR(10),
    KOBER VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.LAGP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LAGP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LEIN (
    MANDT VARCHAR(3),
    LENUM VARCHAR(20),
    LGNUM VARCHAR(3),
    LGTYP VARCHAR(3),
    LGPLA VARCHAR(10)
);
COPY INTO SAP.SAP_ECC.LEIN
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LEIN.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LFA1 (
    MANDT VARCHAR(3),
    LIFNR VARCHAR(10),
    NAME1 VARCHAR(35),
    LAND1 VARCHAR(3),
    ORT01 VARCHAR(35),
    PSTLZ VARCHAR(10)
);
COPY INTO SAP.SAP_ECC.LFA1
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LFA1.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LFB1 (
    MANDT VARCHAR(3),
    LIFNR VARCHAR(10),
    BUKRS VARCHAR(4),
    AKONT VARCHAR(10),
    ZTERM VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.LFB1
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LFB1.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LFM1 (
    MANDT VARCHAR(3),
    LIFNR VARCHAR(10),
    EKORG VARCHAR(4),
    WAERS VARCHAR(5),
    ZTERM VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.LFM1
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LFM1.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LIKP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    LFART VARCHAR(4),
    KUNNR VARCHAR(10),
    WADAT DATE
);
COPY INTO SAP.SAP_ECC.LIKP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LIKP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LIPS (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    LFIMG NUMBER(13,3),
    VRKME VARCHAR(3),
    WERKS VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.LIPS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LIPS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LQUA (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    LQNUM VARCHAR(10),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    LGTYP VARCHAR(3),
    LGPLA VARCHAR(10),
    GESME NUMBER(13,3),
    MEINS VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.LQUA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LQUA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LTAK (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    TESSION VARCHAR(10),
    KESSION DATE,
    BESSION DATE
);
COPY INTO SAP.SAP_ECC.LTAK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LTAK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LTAP (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    TESSION VARCHAR(10),
    TAESSION VARCHAR(4),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    VSOLA NUMBER(13,3),
    MEINS VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.LTAP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LTAP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LTBK (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    TBNUM VARCHAR(10),
    KESSION DATE
);
COPY INTO SAP.SAP_ECC.LTBK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LTBK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.LTBP (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    TBNUM VARCHAR(10),
    TBPOS VARCHAR(4),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    ANFME NUMBER(13,3),
    MEINS VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.LTBP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/LTBP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MAKT (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    SPRAS VARCHAR(1),
    MAKTX VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.MAKT
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MAKT.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MAPL (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    PLNTY VARCHAR(1),
    PLNNR VARCHAR(8),
    PLNAL VARCHAR(2)
);
COPY INTO SAP.SAP_ECC.MAPL
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MAPL.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MARA (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    MTART VARCHAR(4),
    MBRSH VARCHAR(1),
    MATKL VARCHAR(9),
    MEINS VARCHAR(3),
    BRGEW NUMBER(13,3),
    GEWEI VARCHAR(3),
    ERDAT DATE
);
COPY INTO SAP.SAP_ECC.MARA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MARA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MARC (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    DISMM VARCHAR(2),
    DISPO VARCHAR(3),
    BESKZ VARCHAR(1),
    SOBSL VARCHAR(2)
);
COPY INTO SAP.SAP_ECC.MARC
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MARC.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MARD (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    LGORT VARCHAR(4),
    LABST NUMBER(13,3),
    INSME NUMBER(13,3),
    SPEME NUMBER(13,3)
);
COPY INTO SAP.SAP_ECC.MARD
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MARD.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MAST (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    STLAN VARCHAR(1),
    STLNR VARCHAR(8),
    STLAL VARCHAR(2)
);
COPY INTO SAP.SAP_ECC.MAST
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MAST.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MDKP (
    MANDT VARCHAR(3),
    DTNUM VARCHAR(12),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    BEESSION DATE
);
COPY INTO SAP.SAP_ECC.MDKP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MDKP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MDTB (
    MANDT VARCHAR(3),
    DTNUM VARCHAR(12),
    DTLINE VARCHAR(4),
    DELKZ VARCHAR(1),
    PLESSION DATE,
    MESSION NUMBER(13,3),
    MEINS VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.MDTB
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MDTB.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MKPF (
    MANDT VARCHAR(3),
    MBLNR VARCHAR(10),
    MJAHR VARCHAR(4),
    BUDAT DATE,
    BLDAT DATE,
    USNAM VARCHAR(12)
);
COPY INTO SAP.SAP_ECC.MKPF
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MKPF.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MLCD (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    BWKEY VARCHAR(4),
    PESSION VARCHAR(3),
    GJAHR VARCHAR(4),
    CURTP VARCHAR(2),
    WAESSION NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.MLCD
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MLCD.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.MSEG (
    MANDT VARCHAR(3),
    MBLNR VARCHAR(10),
    MJAHR VARCHAR(4),
    ZEILE VARCHAR(4),
    BWART VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    LGORT VARCHAR(4),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.MSEG
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/MSEG.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.OBJK (
    MANDT VARCHAR(3),
    OBKNR VARCHAR(10),
    OBZAE VARCHAR(6),
    EQUNR VARCHAR(18),
    MATNR VARCHAR(18),
    SERNR VARCHAR(18)
);
COPY INTO SAP.SAP_ECC.OBJK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/OBJK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0000 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    MASSN VARCHAR(2),
    MASSG VARCHAR(2),
    STAT2 VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.PA0000
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA0000.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0001 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    BUKRS VARCHAR(4),
    WERKS VARCHAR(4),
    KOSTL VARCHAR(10),
    ORGEH VARCHAR(8),
    PLANS VARCHAR(8)
);
COPY INTO SAP.SAP_ECC.PA0001
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA0001.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0002 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    NACHN VARCHAR(40),
    VORNA VARCHAR(40),
    GBDAT DATE,
    GESCH VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.PA0002
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA0002.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0006 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SUBTY VARCHAR(4),
    STRAS VARCHAR(60),
    ORT01 VARCHAR(40),
    PSTLZ VARCHAR(10),
    LAND1 VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.PA0006
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA0006.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0007 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SCHKZ VARCHAR(8),
    ZESSION NUMBER(5,2)
);
COPY INTO SAP.SAP_ECC.PA0007
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA0007.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0008 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    TRFAR VARCHAR(2),
    TRFGB VARCHAR(2),
    TRFGR VARCHAR(8),
    TRFST VARCHAR(2),
    ANSAL NUMBER(13,2),
    WAESSION VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.PA0008
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA0008.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0014 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    LGART VARCHAR(4),
    BETRG NUMBER(13,2),
    WAESSION VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.PA0014
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA0014.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0015 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    LGART VARCHAR(4),
    BETRG NUMBER(13,2),
    WAESSION VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.PA0015
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA0015.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA2001 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SUBTY VARCHAR(4),
    ABESSION NUMBER(5,2)
);
COPY INTO SAP.SAP_ECC.PA2001
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA2001.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA2002 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SUBTY VARCHAR(4),
    STDAZ NUMBER(5,2)
);
COPY INTO SAP.SAP_ECC.PA2002
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA2002.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA2006 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SUBTY VARCHAR(4),
    ANZHL NUMBER(7,2),
    KESSION NUMBER(7,2)
);
COPY INTO SAP.SAP_ECC.PA2006
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PA2006.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PBED (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    BEDAE VARCHAR(4),
    PDATU DATE,
    PLNMG NUMBER(13,3),
    MEINS VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.PBED
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PBED.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PBIM (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    BEDAE VARCHAR(4),
    VERSB VARCHAR(2)
);
COPY INTO SAP.SAP_ECC.PBIM
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PBIM.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PLAF (
    MANDT VARCHAR(3),
    PLNUM VARCHAR(10),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    GESSION NUMBER(13,3),
    MEINS VARCHAR(3),
    PEDTR DATE,
    PESSION DATE
);
COPY INTO SAP.SAP_ECC.PLAF
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PLAF.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PLKO (
    MANDT VARCHAR(3),
    PLNTY VARCHAR(1),
    PLNNR VARCHAR(8),
    PLNAL VARCHAR(2),
    WERKS VARCHAR(4),
    VERWE VARCHAR(3),
    LOESSION NUMBER(13,3),
    MEINS VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.PLKO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PLKO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.PLPO (
    MANDT VARCHAR(3),
    PLNTY VARCHAR(1),
    PLNNR VARCHAR(8),
    PLNKN VARCHAR(8),
    VORNR VARCHAR(4),
    ARBID VARCHAR(8),
    WERKS VARCHAR(4),
    VGW01 NUMBER(7,1)
);
COPY INTO SAP.SAP_ECC.PLPO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/PLPO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.QMEL (
    MANDT VARCHAR(3),
    QMNUM VARCHAR(12),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    QMDAT DATE,
    QMART VARCHAR(2),
    ERNAM VARCHAR(12)
);
COPY INTO SAP.SAP_ECC.QMEL
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/QMEL.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.RBKP (
    MANDT VARCHAR(3),
    BESSION VARCHAR(10),
    GJAHR VARCHAR(4),
    LIFNR VARCHAR(10),
    BUKRS VARCHAR(4),
    BLDAT DATE,
    BUDAT DATE,
    WAERS VARCHAR(5),
    RMWWR NUMBER(13,2)
);
COPY INTO SAP.SAP_ECC.RBKP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/RBKP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.RESB (
    MANDT VARCHAR(3),
    RSNUM VARCHAR(10),
    RSPOS VARCHAR(4),
    AUFNR VARCHAR(12),
    MATNR VARCHAR(18),
    BDMNG NUMBER(13,3),
    MEINS VARCHAR(3),
    WERKS VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.RESB
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/RESB.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.RLGRAP (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    IVNUM VARCHAR(10),
    IVPOS VARCHAR(4),
    MATNR VARCHAR(18),
    LGTYP VARCHAR(3),
    LGPLA VARCHAR(10)
);
COPY INTO SAP.SAP_ECC.RLGRAP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/RLGRAP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.RSEG (
    MANDT VARCHAR(3),
    BESSION VARCHAR(10),
    GJAHR VARCHAR(4),
    BUZEI VARCHAR(3),
    EBELN VARCHAR(10),
    EBELP VARCHAR(5),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    WRBTR NUMBER(13,2)
);
COPY INTO SAP.SAP_ECC.RSEG
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/RSEG.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.SER01 (
    MANDT VARCHAR(3),
    OBKNR VARCHAR(10),
    LIEF_NR VARCHAR(10),
    POSNR VARCHAR(6)
);
COPY INTO SAP.SAP_ECC.SER01
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/SER01.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.STKO (
    MANDT VARCHAR(3),
    STLTY VARCHAR(1),
    STLNR VARCHAR(8),
    STLAL VARCHAR(2),
    DAESSION DATE,
    BMENG NUMBER(13,3),
    BMEIN VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.STKO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/STKO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.STPO (
    MANDT VARCHAR(3),
    STLTY VARCHAR(1),
    STLNR VARCHAR(8),
    STLKN VARCHAR(8),
    IDNRK VARCHAR(18),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    POSTP VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.STPO
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/STPO.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T000 (
    MANDT VARCHAR(3),
    MTEXT VARCHAR(25),
    CCCATEGORY VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.T000
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T000.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T000T (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    MTEXT VARCHAR(25)
);
COPY INTO SAP.SAP_ECC.T000T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T000T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T001L (
    MANDT VARCHAR(3),
    WERKS VARCHAR(4),
    LGORT VARCHAR(4),
    LGOBE VARCHAR(16)
);
COPY INTO SAP.SAP_ECC.T001L
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T001L.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T001W (
    MANDT VARCHAR(3),
    WERKS VARCHAR(4),
    NAME1 VARCHAR(30),
    BUKRS VARCHAR(4),
    LAND1 VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.T001W
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T001W.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T156 (
    MANDT VARCHAR(3),
    BWART VARCHAR(3),
    SHKZG VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.T156
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T156.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T156T (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    BWART VARCHAR(3),
    BTEXT VARCHAR(20)
);
COPY INTO SAP.SAP_ECC.T156T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T156T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T161 (
    MANDT VARCHAR(3),
    BSART VARCHAR(4),
    BSTYP VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.T161
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T161.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T161T (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    BSART VARCHAR(4),
    BSATX VARCHAR(20)
);
COPY INTO SAP.SAP_ECC.T161T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T161T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T300 (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    LESSION VARCHAR(25)
);
COPY INTO SAP.SAP_ECC.T300
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T300.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T300T (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    SPRAS VARCHAR(1),
    LNUMT VARCHAR(25)
);
COPY INTO SAP.SAP_ECC.T300T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T300T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T527X (
    MANDT VARCHAR(3),
    ORGEH VARCHAR(8),
    SPRAS VARCHAR(1),
    ORGTX VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.T527X
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T527X.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T529T (
    MANDT VARCHAR(3),
    PERSG VARCHAR(1),
    SPRAS VARCHAR(1),
    PTEXT VARCHAR(20)
);
COPY INTO SAP.SAP_ECC.T529T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T529T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T552T (
    MANDT VARCHAR(3),
    SCHKZ VARCHAR(8),
    SPRAS VARCHAR(1),
    RESSION VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.T552T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T552T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T554T (
    MANDT VARCHAR(3),
    MOESSION VARCHAR(4),
    SPRAS VARCHAR(1),
    AESSION VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.T554T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T554T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T556T (
    MANDT VARCHAR(3),
    SUBTY VARCHAR(4),
    SPRAS VARCHAR(1),
    KTEXT VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.T556T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T556T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T685 (
    MANDT VARCHAR(3),
    KSCHL VARCHAR(4),
    KOZGF VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.T685
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T685.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.T685T (
    MANDT VARCHAR(3),
    KSCHL VARCHAR(4),
    SPRAS VARCHAR(1),
    VTEXT VARCHAR(30)
);
COPY INTO SAP.SAP_ECC.T685T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/T685T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TBDLS (
    MANDT VARCHAR(3),
    LOESSION VARCHAR(10),
    SESSION VARCHAR(60)
);
COPY INTO SAP.SAP_ECC.TBDLS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TBDLS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TCURC (
    MANDT VARCHAR(3),
    WAESSION VARCHAR(5),
    IESSION VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.TCURC
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TCURC.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TCURT (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    WAESSION VARCHAR(5),
    LESSION VARCHAR(40)
);
COPY INTO SAP.SAP_ECC.TCURT
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TCURT.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TCURX (
    MANDT VARCHAR(3),
    CURRKEY VARCHAR(5),
    CURRDEC NUMBER(3,0)
);
COPY INTO SAP.SAP_ECC.TCURX
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TCURX.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TJ02 (
    MANDT VARCHAR(3),
    ISTAT VARCHAR(5),
    SESSION VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.TJ02
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TJ02.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TJ02T (
    MANDT VARCHAR(3),
    ISTAT VARCHAR(5),
    SPRAS VARCHAR(1),
    TXT04 VARCHAR(4),
    TXT30 VARCHAR(30)
);
COPY INTO SAP.SAP_ECC.TJ02T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TJ02T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TKA01 (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    BUKRS VARCHAR(4),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.TKA01
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TKA01.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TKT01 (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    SPRAS VARCHAR(1),
    BEZEI VARCHAR(25)
);
COPY INTO SAP.SAP_ECC.TKT01
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TKT01.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TTDS (
    MANDT VARCHAR(3),
    SDABW VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.TTDS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TTDS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TTDST (
    MANDT VARCHAR(3),
    SDABW VARCHAR(4),
    SPRAS VARCHAR(1),
    VTEXT VARCHAR(20)
);
COPY INTO SAP.SAP_ECC.TTDST
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TTDST.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVAK (
    MANDT VARCHAR(3),
    AUART VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.TVAK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TVAK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVAKT (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    AUART VARCHAR(4),
    BEZEI VARCHAR(20)
);
COPY INTO SAP.SAP_ECC.TVAKT
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TVAKT.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVAP (
    MANDT VARCHAR(3),
    PSTYV VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.TVAP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TVAP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVAPT (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    PSTYV VARCHAR(4),
    VTEXT VARCHAR(20)
);
COPY INTO SAP.SAP_ECC.TVAPT
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TVAPT.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVLK (
    MANDT VARCHAR(3),
    LFART VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.TVLK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TVLK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVLKT (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    LFART VARCHAR(4),
    VTEXT VARCHAR(20)
);
COPY INTO SAP.SAP_ECC.TVLKT
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/TVLKT.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.USR02 (
    MANDT VARCHAR(3),
    BNAME VARCHAR(12),
    USTYP VARCHAR(1),
    CLASS VARCHAR(12),
    TRDAT DATE,
    LTIME TIME
);
COPY INTO SAP.SAP_ECC.USR02
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/USR02.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBAK (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    AUART VARCHAR(4),
    VKORG VARCHAR(4),
    VTWEG VARCHAR(2),
    SPART VARCHAR(2),
    KUNNR VARCHAR(10),
    ERDAT DATE,
    NETWR NUMBER(13,2),
    WAERK VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.VBAK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBAK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBAP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    KWMENG NUMBER(13,3),
    VRKME VARCHAR(3),
    NETWR NUMBER(13,2),
    WERKS VARCHAR(4)
);
COPY INTO SAP.SAP_ECC.VBAP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBAP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBEP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    ETENR VARCHAR(4),
    EDATU DATE,
    WMENG NUMBER(13,3),
    VRKME VARCHAR(3)
);
COPY INTO SAP.SAP_ECC.VBEP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBEP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBFA (
    MANDT VARCHAR(3),
    VBELV VARCHAR(10),
    POSNV VARCHAR(6),
    VBELN VARCHAR(10),
    POSNN VARCHAR(6),
    VBTYP_N VARCHAR(1),
    ERDAT DATE
);
COPY INTO SAP.SAP_ECC.VBFA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBFA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBKD (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    ZTERM VARCHAR(4),
    INCO1 VARCHAR(3),
    INCO2 VARCHAR(28)
);
COPY INTO SAP.SAP_ECC.VBKD
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBKD.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBPA (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    PARVW VARCHAR(2),
    KUNNR VARCHAR(10),
    LIFNR VARCHAR(10)
);
COPY INTO SAP.SAP_ECC.VBPA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBPA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBRK (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    FKART VARCHAR(4),
    KUNNR VARCHAR(10),
    FKDAT DATE,
    NETWR NUMBER(13,2),
    WAERK VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.VBRK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBRK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBRP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    FKIMG NUMBER(13,3),
    VRKME VARCHAR(3),
    NETWR NUMBER(13,2)
);
COPY INTO SAP.SAP_ECC.VBRP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBRP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBUK (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    GBSTK VARCHAR(1),
    LFSTK VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.VBUK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBUK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBUP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    GBSTA VARCHAR(1),
    LFSTA VARCHAR(1)
);
COPY INTO SAP.SAP_ECC.VBUP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VBUP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VFKN (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    VFKNI VARCHAR(6),
    KSCHL VARCHAR(4),
    KBETR NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.VFKN
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VFKN.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VFKP (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    ABESSION VARCHAR(10),
    WAESSION NUMBER(13,2),
    WAERS VARCHAR(5)
);
COPY INTO SAP.SAP_ECC.VFKP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VFKP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VTFA (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    TPNUM VARCHAR(4),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6)
);
COPY INTO SAP.SAP_ECC.VTFA
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VTFA.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VTTK (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    SDABW VARCHAR(4),
    VSART VARCHAR(2),
    TDLNR VARCHAR(10),
    DESSION DATE
);
COPY INTO SAP.SAP_ECC.VTTK
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VTTK.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VTTP (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    TPNUM VARCHAR(4),
    VBELN VARCHAR(10)
);
COPY INTO SAP.SAP_ECC.VTTP
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VTTP.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.VTTS (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    TSNUM VARCHAR(4),
    TSRFO VARCHAR(4),
    KNESSION VARCHAR(10)
);
COPY INTO SAP.SAP_ECC.VTTS
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/VTTS.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

