-- SAP ECC Data Dictionary load script
-- Creates matching Snowflake tables in SAP.SAP_ECC and loads the CSV files from sap/dd

CREATE OR REPLACE DATABASE SAP;
CREATE OR REPLACE SCHEMA SAP.SAP_ECC;
USE SCHEMA SAP.SAP_ECC;

CREATE OR REPLACE FILE FORMAT SAP.SAP_ECC.SAP_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('')
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE SAP.SAP_ECC.SAP_DATA_STAGE
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT;

COPY FILES INTO @SAP.SAP_ECC.SAP_DATA_STAGE
    FROM 'snow://workspace/USER$.PUBLIC."sap-demo"/versions/live/sap/dd/'
    PATTERN = '.*[.]csv';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD01L (
    DOMNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    DDLANGUAGE VARCHAR,
    DATATYPE VARCHAR,
    LENG VARCHAR,
    OUTPUTLEN VARCHAR,
    DECIMALS VARCHAR,
    SIGNFLAG VARCHAR
);
COPY INTO SAP.SAP_ECC.DD01L
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD01L.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD02L (
    TABNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    TABCLASS VARCHAR,
    SQLTAB VARCHAR,
    AUTHCLASS VARCHAR,
    MASTERLANG VARCHAR,
    CONTFLAG VARCHAR,
    MATEFLAG VARCHAR,
    BUFFERED VARCHAR,
    EXCLASS VARCHAR
);
COPY INTO SAP.SAP_ECC.DD02L
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD02L.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD02T (
    TABNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    DDLANGUAGE VARCHAR,
    DDTEXT VARCHAR
);
COPY INTO SAP.SAP_ECC.DD02T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD02T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD03L (
    TABNAME VARCHAR,
    FIELDNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    POSITION VARCHAR,
    KEYFLAG VARCHAR,
    DATATYPE VARCHAR,
    LENG VARCHAR,
    DECIMALS VARCHAR,
    DOMNAME VARCHAR,
    ROLLNAME VARCHAR
);
COPY INTO SAP.SAP_ECC.DD03L
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD03L.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD03T (
    TABNAME VARCHAR,
    FIELDNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    DDLANGUAGE VARCHAR,
    DDTEXT VARCHAR
);
COPY INTO SAP.SAP_ECC.DD03T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD03T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD04L (
    ROLLNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    DOMNAME VARCHAR,
    DATATYPE VARCHAR,
    LENG VARCHAR,
    OUTPUTLEN VARCHAR,
    DECIMALS VARCHAR,
    SIGNFLAG VARCHAR
);
COPY INTO SAP.SAP_ECC.DD04L
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD04L.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD04T (
    ROLLNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    DDLANGUAGE VARCHAR,
    DDTEXT VARCHAR
);
COPY INTO SAP.SAP_ECC.DD04T
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD04T.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD05S (
    TABNAME VARCHAR,
    FIELDNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    FORTABLE VARCHAR,
    FORKEY VARCHAR,
    CHECKTABLE VARCHAR,
    CHECKFIELD VARCHAR
);
COPY INTO SAP.SAP_ECC.DD05S
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD05S.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD07L (
    DOMNAME VARCHAR,
    AS4LOCAL VARCHAR,
    AS4VERS VARCHAR,
    VALPOS VARCHAR,
    DDLANGUAGE VARCHAR,
    VALUE VARCHAR,
    DDTEXT VARCHAR
);
COPY INTO SAP.SAP_ECC.DD07L
    FROM @SAP.SAP_ECC.SAP_DATA_STAGE/DD07L.csv
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';
