-- SAP ECC Table Creation and Data Loading Script
-- Generated from sap/dd/DD03L.csv definitions
-- Data loaded from sap/data/*.csv

-- Step 1: Create database and schema
CREATE DATABASE IF NOT EXISTS SAP;
CREATE SCHEMA IF NOT EXISTS SAP.SAP_ECC;
USE SCHEMA SAP.SAP_ECC;

-- Step 2: Create file format for CSV loading
CREATE OR REPLACE FILE FORMAT SAP.SAP_ECC.SAP_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'YYYY-MM-DD';

-- Step 3: Create tables
CREATE OR REPLACE TABLE SAP.SAP_ECC.AFKO (
    MANDT VARCHAR(3),
    AUFNR VARCHAR(12),
    DESSION VARCHAR(8),
    STLNR VARCHAR(8),
    GAMNG NUMBER(13,3),
    GMEIN VARCHAR(3),
    GLTRS DATE,
    GLTRP DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.AFPO (
    MANDT VARCHAR(3),
    AUFNR VARCHAR(12),
    POSNR VARCHAR(4),
    MATNR VARCHAR(18),
    PSMNG NUMBER(13,3),
    MEINS VARCHAR(3),
    WERKS VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.AFVC (
    MANDT VARCHAR(3),
    AUFPL VARCHAR(10),
    APLZL VARCHAR(8),
    VORNR VARCHAR(4),
    ARBID VARCHAR(8),
    WERKS VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.AFVV (
    MANDT VARCHAR(3),
    AUFPL VARCHAR(10),
    APLZL VARCHAR(8),
    MGVRG NUMBER(13,3),
    MEINH VARCHAR(3),
    DAESSION VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.AGR_TEXTS (
    MANDT VARCHAR(3),
    AGR_NAME VARCHAR(30),
    SPRAS VARCHAR(1),
    LINE VARCHAR(3),
    TEXT VARCHAR(80)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.AGR_USERS (
    MANDT VARCHAR(3),
    AGR_NAME VARCHAR(30),
    UNAME VARCHAR(12),
    FROM_DAT DATE,
    TO_DAT DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.ANEP (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    ANLN1 VARCHAR(12),
    ANLN2 VARCHAR(4),
    GJAHR VARCHAR(4),
    LNRAN VARCHAR(3),
    AFABE VARCHAR(2),
    BWASL VARCHAR(3),
    ANBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.ANLA (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    ANLN1 VARCHAR(12),
    ANLN2 VARCHAR(4),
    ANLKL VARCHAR(8),
    TXT50 VARCHAR(50),
    AKTIV DATE,
    DEAKT DATE,
    KOSTL VARCHAR(10),
    WERKS VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.AUFK (
    MANDT VARCHAR(3),
    AUFNR VARCHAR(12),
    AUTYP VARCHAR(2),
    BUKRS VARCHAR(4),
    WERKS VARCHAR(4),
    KOSTL VARCHAR(10),
    ERDAT DATE,
    ERNAM VARCHAR(12)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BALDAT (
    MANDT VARCHAR(3),
    LOG_HANDLE VARCHAR(22),
    LOGNUMBER VARCHAR(6),
    MSG_DATA VARCHAR(200)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BALHDR (
    MANDT VARCHAR(3),
    LOG_HANDLE VARCHAR(22),
    OBJECT VARCHAR(20),
    SUBOBJECT VARCHAR(20),
    ALDATE DATE,
    ALTIME VARCHAR(6),
    ALUSER VARCHAR(12)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BDCP2 (
    MANDT VARCHAR(3),
    MESTYP VARCHAR(30),
    CPIDENT VARCHAR(26),
    TABNAME VARCHAR(30),
    TABKEY VARCHAR(70),
    CRESSION_DATE DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BKPF (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    BELNR VARCHAR(10),
    GJAHR VARCHAR(4),
    BLART VARCHAR(2),
    BUDAT DATE,
    BLDAT DATE,
    WAERS VARCHAR(5),
    USNAM VARCHAR(12)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSAD (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    KUNNR VARCHAR(10),
    UMSKS VARCHAR(1),
    AUGDT DATE,
    AUGBL VARCHAR(10),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSAK (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    LIFNR VARCHAR(10),
    UMSKS VARCHAR(1),
    AUGDT DATE,
    AUGBL VARCHAR(10),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSAS (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    HKONT VARCHAR(10),
    AUGDT DATE,
    AUGBL VARCHAR(10),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSEG (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    BELNR VARCHAR(10),
    GJAHR VARCHAR(4),
    BUZEI VARCHAR(3),
    KOART VARCHAR(1),
    SHKZG VARCHAR(1),
    DMBTR NUMBER(13,2),
    WRBTR NUMBER(13,2),
    HKONT VARCHAR(10),
    KOSTL VARCHAR(10),
    MATNR VARCHAR(18)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSID (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    KUNNR VARCHAR(10),
    UMSKS VARCHAR(1),
    BUDAT DATE,
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.BSIK (
    MANDT VARCHAR(3),
    BUKRS VARCHAR(4),
    LIFNR VARCHAR(10),
    UMSKS VARCHAR(1),
    BUDAT DATE,
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CDHDR (
    MANDT VARCHAR(3),
    OBJECTCLAS VARCHAR(15),
    OBJECTID VARCHAR(90),
    CHANGENR VARCHAR(10),
    USERNAME VARCHAR(12),
    UDATE DATE,
    UTIME VARCHAR(6),
    TCODE VARCHAR(20)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CDPOS (
    MANDT VARCHAR(3),
    OBJECTCLAS VARCHAR(15),
    OBJECTID VARCHAR(90),
    CHANGENR VARCHAR(10),
    TABNAME VARCHAR(30),
    TABKEY VARCHAR(70),
    FNAME VARCHAR(30),
    CHNGIND VARCHAR(1),
    VALUE_NEW VARCHAR(254),
    VALUE_OLD VARCHAR(254)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CE1XXXX (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    PESSION VARCHAR(10),
    KUNNR VARCHAR(10),
    MATNR VARCHAR(18),
    VKORG VARCHAR(4),
    WERKS VARCHAR(4),
    PERDE VARCHAR(3),
    GJAHR VARCHAR(4),
    VV010 NUMBER(13,2),
    TWAER VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CE2XXXX (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    PESSION VARCHAR(10),
    KUNNR VARCHAR(10),
    MATNR VARCHAR(18),
    VKORG VARCHAR(4),
    WERKS VARCHAR(4),
    PESSION2 VARCHAR(3),
    GJAHR VARCHAR(4),
    VV010 NUMBER(13,2),
    TWAER VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.COBK (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    BESSION VARCHAR(10),
    GJAHR VARCHAR(4),
    BLDAT DATE,
    BUDAT DATE,
    BLTXT VARCHAR(25)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.COEP (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    BELNR VARCHAR(10),
    GJAHR VARCHAR(4),
    BUZEI VARCHAR(3),
    KSTAR VARCHAR(10),
    KOSTL VARCHAR(10),
    WRBTR NUMBER(13,2),
    TWAER VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.COSP (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    OBJNR VARCHAR(22),
    GJAHR VARCHAR(4),
    KSTAR VARCHAR(10),
    WTG001 NUMBER(13,2),
    TWAER VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.COSS (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    OBJNR VARCHAR(22),
    GJAHR VARCHAR(4),
    KSTAR VARCHAR(10),
    WTG001 NUMBER(13,2),
    TWAER VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CRHD (
    MANDT VARCHAR(3),
    OBJID VARCHAR(8),
    OBJTY VARCHAR(2),
    WERKS VARCHAR(4),
    ARBPL VARCHAR(8),
    VERWE VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CRTX (
    MANDT VARCHAR(3),
    OBJID VARCHAR(8),
    SPRAS VARCHAR(1),
    KTEXT VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKA (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KSTAR VARCHAR(10),
    DATBI DATE,
    KATYP VARCHAR(2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKB (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KSTAR VARCHAR(10),
    DATBI DATE,
    KATYP VARCHAR(2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKS (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KOSTL VARCHAR(10),
    DATBI DATE,
    BUKRS VARCHAR(4),
    KOSAR VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKT (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KOSTL VARCHAR(10),
    SPRAS VARCHAR(1),
    DATBI DATE,
    KTEXT VARCHAR(20),
    LTEXT VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.CSKU (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    KSTAR VARCHAR(10),
    SPRAS VARCHAR(1),
    KTEXT VARCHAR(20),
    LTEXT VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD02L (
    TABNAME VARCHAR(30),
    AS4LOCAL VARCHAR(1),
    AS4VERS VARCHAR(4),
    TABCLASS VARCHAR(8),
    SQLTAB VARCHAR(30),
    AUTHCLASS VARCHAR(2),
    MASTERLANG VARCHAR(1),
    CONTFLAG VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.DD03L (
    TABNAME VARCHAR(30),
    FIELDNAME VARCHAR(30),
    AS4LOCAL VARCHAR(1),
    AS4VERS VARCHAR(4),
    POSITION VARCHAR(4),
    KEYFLAG VARCHAR(1),
    DATATYPE VARCHAR(4),
    LENG VARCHAR(6),
    DECIMALS VARCHAR(6),
    DOMNAME VARCHAR(30),
    ROLLNAME VARCHAR(30)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EBAN (
    MANDT VARCHAR(3),
    BANFN VARCHAR(10),
    BNFPO VARCHAR(5),
    MATNR VARCHAR(18),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    WERKS VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EDID4 (
    MANDT VARCHAR(3),
    DOCNUM VARCHAR(16),
    COUNTER VARCHAR(6),
    SEGNAM VARCHAR(27),
    SDATA VARCHAR(1000)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EDIDC (
    MANDT VARCHAR(3),
    DOCNUM VARCHAR(16),
    MESTYP VARCHAR(30),
    IDOCTP VARCHAR(30),
    STATUS VARCHAR(2),
    CREDAT DATE,
    CRETIM VARCHAR(6),
    SNDPRT VARCHAR(2),
    SNDPRN VARCHAR(10),
    RCVPRT VARCHAR(2),
    RCVPRN VARCHAR(10)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EINA (
    MANDT VARCHAR(3),
    INFNR VARCHAR(10),
    MATNR VARCHAR(18),
    LIFNR VARCHAR(10),
    LOEKZ VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EINE (
    MANDT VARCHAR(3),
    INFNR VARCHAR(10),
    EKORG VARCHAR(4),
    WERKS VARCHAR(4),
    NETPR NUMBER(13,2),
    WAERS VARCHAR(5),
    PEINH NUMBER(5,0)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EKBE (
    MANDT VARCHAR(3),
    EBELN VARCHAR(10),
    EBELP VARCHAR(5),
    ZEKKN VARCHAR(5),
    VGABE VARCHAR(1),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    BUZEI VARCHAR(3),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EKET (
    MANDT VARCHAR(3),
    EBELN VARCHAR(10),
    EBELP VARCHAR(5),
    ETENR VARCHAR(4),
    EINDT DATE,
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    WEMNG NUMBER(13,3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EKKO (
    MANDT VARCHAR(3),
    EBELN VARCHAR(10),
    BUKRS VARCHAR(4),
    BSTYP VARCHAR(1),
    BSART VARCHAR(4),
    LIFNR VARCHAR(10),
    EKORG VARCHAR(4),
    BEDAT DATE,
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.EKPO (
    MANDT VARCHAR(3),
    EBELN VARCHAR(10),
    EBELP VARCHAR(5),
    MATNR VARCHAR(18),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    NETPR NUMBER(13,2),
    WERKS VARCHAR(4),
    LIFNR VARCHAR(10)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.FAGLFLEXA (
    MANDT VARCHAR(3),
    RLDNR VARCHAR(2),
    BUKRS VARCHAR(4),
    GJAHR VARCHAR(4),
    BELNR VARCHAR(10),
    DOCLN VARCHAR(6),
    RACCT VARCHAR(10),
    KOSTL VARCHAR(10),
    HSL NUMBER(13,2),
    RHCUR VARCHAR(5),
    BUDAT DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.HRP1000 (
    MANDT VARCHAR(3),
    PLVAR VARCHAR(2),
    OTYPE VARCHAR(2),
    OBJID VARCHAR(8),
    BEGDA DATE,
    ENDDA DATE,
    STEXT VARCHAR(40),
    LANGU VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.HRP1001 (
    MANDT VARCHAR(3),
    PLVAR VARCHAR(2),
    OTYPE VARCHAR(2),
    OBJID VARCHAR(8),
    SUBTY VARCHAR(4),
    BEGDA DATE,
    ENDDA DATE,
    SCLAS VARCHAR(2),
    SOBID VARCHAR(8)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.HRP1002 (
    MANDT VARCHAR(3),
    PLVAR VARCHAR(2),
    OTYPE VARCHAR(2),
    OBJID VARCHAR(8),
    BEGDA DATE,
    ENDDA DATE,
    DESSION VARCHAR(255)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.INFO (
    MANDT VARCHAR(3),
    INFNR VARCHAR(10),
    MATNR VARCHAR(18),
    LIFNR VARCHAR(10),
    LOEKZ VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.JEST (
    MANDT VARCHAR(3),
    OBJNR VARCHAR(22),
    STAT VARCHAR(5),
    INACT VARCHAR(1),
    CHGNR VARCHAR(6)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.KEKO (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    KALKA VARCHAR(1),
    KADKY DATE,
    TVERS VARCHAR(2),
    LOSGR NUMBER(13,3),
    MEINS VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.KEPH (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    KALKA VARCHAR(1),
    KADKY DATE,
    TVERS VARCHAR(2),
    ELEHK VARCHAR(2),
    KST001 NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.KNA1 (
    MANDT VARCHAR(3),
    KUNNR VARCHAR(10),
    NAME1 VARCHAR(35),
    LAND1 VARCHAR(3),
    ORT01 VARCHAR(35),
    PSTLZ VARCHAR(10),
    STRAS VARCHAR(35)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.KNVV (
    MANDT VARCHAR(3),
    KUNNR VARCHAR(10),
    VKORG VARCHAR(4),
    VTWEG VARCHAR(2),
    SPART VARCHAR(2),
    KDGRP VARCHAR(2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.KONV (
    MANDT VARCHAR(3),
    KNUMV VARCHAR(10),
    KPOSN VARCHAR(6),
    STUNR VARCHAR(3),
    ZAESSION VARCHAR(3),
    KSCHL VARCHAR(4),
    KBETR NUMBER(13,2),
    WAERS VARCHAR(5),
    KWERT NUMBER(13,2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LAGP (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    LGTYP VARCHAR(3),
    LGPLA VARCHAR(10),
    KOBER VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LEIN (
    MANDT VARCHAR(3),
    LENUM VARCHAR(20),
    LGNUM VARCHAR(3),
    LGTYP VARCHAR(3),
    LGPLA VARCHAR(10)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LFA1 (
    MANDT VARCHAR(3),
    LIFNR VARCHAR(10),
    NAME1 VARCHAR(35),
    LAND1 VARCHAR(3),
    ORT01 VARCHAR(35),
    PSTLZ VARCHAR(10)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LFB1 (
    MANDT VARCHAR(3),
    LIFNR VARCHAR(10),
    BUKRS VARCHAR(4),
    AKONT VARCHAR(10),
    ZTERM VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LFM1 (
    MANDT VARCHAR(3),
    LIFNR VARCHAR(10),
    EKORG VARCHAR(4),
    WAERS VARCHAR(5),
    ZTERM VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LIKP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    LFART VARCHAR(4),
    KUNNR VARCHAR(10),
    WADAT DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LIPS (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    LFIMG NUMBER(13,3),
    VRKME VARCHAR(3),
    WERKS VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LQUA (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    LQNUM VARCHAR(10),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    LGTYP VARCHAR(3),
    LGPLA VARCHAR(10),
    GESME NUMBER(13,3),
    MEINS VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LTAK (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    TESSION VARCHAR(10),
    KESSION DATE,
    BESSION DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LTAP (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    TESSION VARCHAR(10),
    TAESSION VARCHAR(4),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    VSOLA NUMBER(13,3),
    MEINS VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LTBK (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    TBNUM VARCHAR(10),
    KESSION DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.LTBP (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    TBNUM VARCHAR(10),
    TBPOS VARCHAR(4),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    ANFME NUMBER(13,3),
    MEINS VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MAKT (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    SPRAS VARCHAR(1),
    MAKTX VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MAPL (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    PLNTY VARCHAR(1),
    PLNNR VARCHAR(8),
    PLNAL VARCHAR(2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MARA (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    MTART VARCHAR(4),
    MBRSH VARCHAR(1),
    MATKL VARCHAR(9),
    MEINS VARCHAR(3),
    BRGEW NUMBER(13,3),
    GEWEI VARCHAR(3),
    ERDAT DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MARC (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    DISMM VARCHAR(2),
    DISPO VARCHAR(3),
    BESKZ VARCHAR(1),
    SOBSL VARCHAR(2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MARD (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    LGORT VARCHAR(4),
    LABST NUMBER(13,3),
    INSME NUMBER(13,3),
    SPEME NUMBER(13,3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MAST (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    STLAN VARCHAR(1),
    STLNR VARCHAR(8),
    STLAL VARCHAR(2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MDKP (
    MANDT VARCHAR(3),
    DTNUM VARCHAR(12),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    BEESSION DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MDTB (
    MANDT VARCHAR(3),
    DTNUM VARCHAR(12),
    DTLINE VARCHAR(4),
    DELKZ VARCHAR(1),
    PLESSION DATE,
    MESSION NUMBER(13,3),
    MEINS VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MKPF (
    MANDT VARCHAR(3),
    MBLNR VARCHAR(10),
    MJAHR VARCHAR(4),
    BUDAT DATE,
    BLDAT DATE,
    USNAM VARCHAR(12)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MLCD (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    BWKEY VARCHAR(4),
    PESSION VARCHAR(3),
    GJAHR VARCHAR(4),
    CURTP VARCHAR(2),
    WAESSION NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.MSEG (
    MANDT VARCHAR(3),
    MBLNR VARCHAR(10),
    MJAHR VARCHAR(4),
    ZEILE VARCHAR(4),
    BWART VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    LGORT VARCHAR(4),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    DMBTR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.OBJK (
    MANDT VARCHAR(3),
    OBKNR VARCHAR(10),
    OBZAE VARCHAR(6),
    EQUNR VARCHAR(18),
    MATNR VARCHAR(18),
    SERNR VARCHAR(18)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0000 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    MASSN VARCHAR(2),
    MASSG VARCHAR(2),
    STAT2 VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0001 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    BUKRS VARCHAR(4),
    WERKS VARCHAR(4),
    KOSTL VARCHAR(10),
    ORGEH VARCHAR(8),
    PLANS VARCHAR(8)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0002 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    NACHN VARCHAR(40),
    VORNA VARCHAR(40),
    GBDAT DATE,
    GESCH VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0006 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SUBTY VARCHAR(4),
    STRAS VARCHAR(60),
    ORT01 VARCHAR(40),
    PSTLZ VARCHAR(10),
    LAND1 VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0007 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SCHKZ VARCHAR(8),
    ZESSION NUMBER(5,2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0008 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    TRFAR VARCHAR(2),
    TRFGB VARCHAR(2),
    TRFGR VARCHAR(8),
    TRFST VARCHAR(2),
    ANSAL NUMBER(13,2),
    WAESSION VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0014 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    LGART VARCHAR(4),
    BETRG NUMBER(13,2),
    WAESSION VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA0015 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    LGART VARCHAR(4),
    BETRG NUMBER(13,2),
    WAESSION VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA2001 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SUBTY VARCHAR(4),
    ABESSION NUMBER(5,2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA2002 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SUBTY VARCHAR(4),
    STDAZ NUMBER(5,2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PA2006 (
    MANDT VARCHAR(3),
    PERNR VARCHAR(8),
    ENDDA DATE,
    BEGDA DATE,
    SUBTY VARCHAR(4),
    ANZHL NUMBER(7,2),
    KESSION NUMBER(7,2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PBED (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    BEDAE VARCHAR(4),
    PDATU DATE,
    PLNMG NUMBER(13,3),
    MEINS VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PBIM (
    MANDT VARCHAR(3),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    BEDAE VARCHAR(4),
    VERSB VARCHAR(2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PLAF (
    MANDT VARCHAR(3),
    PLNUM VARCHAR(10),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    GESSION NUMBER(13,3),
    MEINS VARCHAR(3),
    PEDTR DATE,
    PESSION DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PLKO (
    MANDT VARCHAR(3),
    PLNTY VARCHAR(1),
    PLNNR VARCHAR(8),
    PLNAL VARCHAR(2),
    WERKS VARCHAR(4),
    VERWE VARCHAR(3),
    LOESSION NUMBER(13,3),
    MEINS VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.PLPO (
    MANDT VARCHAR(3),
    PLNTY VARCHAR(1),
    PLNNR VARCHAR(8),
    PLNKN VARCHAR(8),
    VORNR VARCHAR(4),
    ARBID VARCHAR(8),
    WERKS VARCHAR(4),
    VGW01 NUMBER(7,1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.QMEL (
    MANDT VARCHAR(3),
    QMNUM VARCHAR(12),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    QMDAT DATE,
    QMART VARCHAR(2),
    ERNAM VARCHAR(12)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.RBKP (
    MANDT VARCHAR(3),
    BESSION VARCHAR(10),
    GJAHR VARCHAR(4),
    LIFNR VARCHAR(10),
    BUKRS VARCHAR(4),
    BLDAT DATE,
    BUDAT DATE,
    WAERS VARCHAR(5),
    RMWWR NUMBER(13,2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.RESB (
    MANDT VARCHAR(3),
    RSNUM VARCHAR(10),
    RSPOS VARCHAR(4),
    AUFNR VARCHAR(12),
    MATNR VARCHAR(18),
    BDMNG NUMBER(13,3),
    MEINS VARCHAR(3),
    WERKS VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.RLGRAP (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    IVNUM VARCHAR(10),
    IVPOS VARCHAR(4),
    MATNR VARCHAR(18),
    LGTYP VARCHAR(3),
    LGPLA VARCHAR(10)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.RSEG (
    MANDT VARCHAR(3),
    BESSION VARCHAR(10),
    GJAHR VARCHAR(4),
    BUZEI VARCHAR(3),
    EBELN VARCHAR(10),
    EBELP VARCHAR(5),
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    WRBTR NUMBER(13,2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.SER01 (
    MANDT VARCHAR(3),
    OBKNR VARCHAR(10),
    LIEF_NR VARCHAR(10),
    POSNR VARCHAR(6)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.STKO (
    MANDT VARCHAR(3),
    STLTY VARCHAR(1),
    STLNR VARCHAR(8),
    STLAL VARCHAR(2),
    DAESSION DATE,
    BMENG NUMBER(13,3),
    BMEIN VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.STPO (
    MANDT VARCHAR(3),
    STLTY VARCHAR(1),
    STLNR VARCHAR(8),
    STLKN VARCHAR(8),
    IDNRK VARCHAR(18),
    MENGE NUMBER(13,3),
    MEINS VARCHAR(3),
    POSTP VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T000 (
    MANDT VARCHAR(3),
    MTEXT VARCHAR(25),
    CCCATEGORY VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T000T (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    MTEXT VARCHAR(25)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T001L (
    MANDT VARCHAR(3),
    WERKS VARCHAR(4),
    LGORT VARCHAR(4),
    LGOBE VARCHAR(16)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T001W (
    MANDT VARCHAR(3),
    WERKS VARCHAR(4),
    NAME1 VARCHAR(30),
    BUKRS VARCHAR(4),
    LAND1 VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T156 (
    MANDT VARCHAR(3),
    BWART VARCHAR(3),
    SHKZG VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T156T (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    BWART VARCHAR(3),
    BTEXT VARCHAR(20)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T161 (
    MANDT VARCHAR(3),
    BSART VARCHAR(4),
    BSTYP VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T161T (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    BSART VARCHAR(4),
    BSATX VARCHAR(20)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T300 (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    LESSION VARCHAR(25)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T300T (
    MANDT VARCHAR(3),
    LGNUM VARCHAR(3),
    SPRAS VARCHAR(1),
    LNUMT VARCHAR(25)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T527X (
    MANDT VARCHAR(3),
    ORGEH VARCHAR(8),
    SPRAS VARCHAR(1),
    ORGTX VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T529T (
    MANDT VARCHAR(3),
    PERSG VARCHAR(1),
    SPRAS VARCHAR(1),
    PTEXT VARCHAR(20)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T552T (
    MANDT VARCHAR(3),
    SCHKZ VARCHAR(8),
    SPRAS VARCHAR(1),
    RESSION VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T554T (
    MANDT VARCHAR(3),
    MOESSION VARCHAR(4),
    SPRAS VARCHAR(1),
    AESSION VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T556T (
    MANDT VARCHAR(3),
    SUBTY VARCHAR(4),
    SPRAS VARCHAR(1),
    KTEXT VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T685 (
    MANDT VARCHAR(3),
    KSCHL VARCHAR(4),
    KOZGF VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.T685T (
    MANDT VARCHAR(3),
    KSCHL VARCHAR(4),
    SPRAS VARCHAR(1),
    VTEXT VARCHAR(30)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TBDLS (
    MANDT VARCHAR(3),
    LOESSION VARCHAR(10),
    SESSION VARCHAR(60)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TCURC (
    MANDT VARCHAR(3),
    WAESSION VARCHAR(5),
    IESSION VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TCURT (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    WAESSION VARCHAR(5),
    LESSION VARCHAR(40)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TCURX (
    MANDT VARCHAR(3),
    CURRKEY VARCHAR(5),
    CURRDEC NUMBER(3,0)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TJ02 (
    MANDT VARCHAR(3),
    ISTAT VARCHAR(5),
    SESSION VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TJ02T (
    MANDT VARCHAR(3),
    ISTAT VARCHAR(5),
    SPRAS VARCHAR(1),
    TXT04 VARCHAR(4),
    TXT30 VARCHAR(30)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TKA01 (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    BUKRS VARCHAR(4),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TKT01 (
    MANDT VARCHAR(3),
    KOKRS VARCHAR(4),
    SPRAS VARCHAR(1),
    BEZEI VARCHAR(25)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TTDS (
    MANDT VARCHAR(3),
    SDABW VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TTDST (
    MANDT VARCHAR(3),
    SDABW VARCHAR(4),
    SPRAS VARCHAR(1),
    VTEXT VARCHAR(20)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVAK (
    MANDT VARCHAR(3),
    AUART VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVAKT (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    AUART VARCHAR(4),
    BEZEI VARCHAR(20)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVAP (
    MANDT VARCHAR(3),
    PSTYV VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVAPT (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    PSTYV VARCHAR(4),
    VTEXT VARCHAR(20)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVLK (
    MANDT VARCHAR(3),
    LFART VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.TVLKT (
    MANDT VARCHAR(3),
    SPRAS VARCHAR(1),
    LFART VARCHAR(4),
    VTEXT VARCHAR(20)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.USR02 (
    MANDT VARCHAR(3),
    BNAME VARCHAR(12),
    USTYP VARCHAR(1),
    CLASS VARCHAR(12),
    TRDAT DATE,
    LTIME VARCHAR(6)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBAK (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    AUART VARCHAR(4),
    VKORG VARCHAR(4),
    VTWEG VARCHAR(2),
    SPART VARCHAR(2),
    KUNNR VARCHAR(10),
    ERDAT DATE,
    NETWR NUMBER(13,2),
    WAERK VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBAP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    KWMENG NUMBER(13,3),
    VRKME VARCHAR(3),
    NETWR NUMBER(13,2),
    WERKS VARCHAR(4)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBEP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    ETENR VARCHAR(4),
    EDATU DATE,
    WMENG NUMBER(13,3),
    VRKME VARCHAR(3)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBFA (
    MANDT VARCHAR(3),
    VBELV VARCHAR(10),
    POSNV VARCHAR(6),
    VBELN VARCHAR(10),
    POSNN VARCHAR(6),
    VBTYP_N VARCHAR(1),
    ERDAT DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBKD (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    ZTERM VARCHAR(4),
    INCO1 VARCHAR(3),
    INCO2 VARCHAR(28)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBPA (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    PARVW VARCHAR(2),
    KUNNR VARCHAR(10),
    LIFNR VARCHAR(10)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBRK (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    FKART VARCHAR(4),
    KUNNR VARCHAR(10),
    FKDAT DATE,
    NETWR NUMBER(13,2),
    WAERK VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBRP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    FKIMG NUMBER(13,3),
    VRKME VARCHAR(3),
    NETWR NUMBER(13,2)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBUK (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    GBSTK VARCHAR(1),
    LFSTK VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VBUP (
    MANDT VARCHAR(3),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    GBSTA VARCHAR(1),
    LFSTA VARCHAR(1)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VFKN (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    VFKNI VARCHAR(6),
    KSCHL VARCHAR(4),
    KBETR NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VFKP (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    ABESSION VARCHAR(10),
    WAESSION NUMBER(13,2),
    WAERS VARCHAR(5)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VTFA (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    TPNUM VARCHAR(4),
    VBELN VARCHAR(10),
    POSNR VARCHAR(6)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VTTK (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    SDABW VARCHAR(4),
    VSART VARCHAR(2),
    TDLNR VARCHAR(10),
    DESSION DATE
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VTTP (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    TPNUM VARCHAR(4),
    VBELN VARCHAR(10)
);

CREATE OR REPLACE TABLE SAP.SAP_ECC.VTTS (
    MANDT VARCHAR(3),
    TKNUM VARCHAR(10),
    TSNUM VARCHAR(4),
    TSRFO VARCHAR(4),
    KNESSION VARCHAR(10)
);

-- Step 4: Load data from CSV files
COPY INTO SAP.SAP_ECC.AFKO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/AFKO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.AFPO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/AFPO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.AFVC
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/AFVC.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.AFVV
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/AFVV.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.AGR_TEXTS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/AGR_TEXTS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.AGR_USERS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/AGR_USERS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.ANEP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/ANEP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.ANLA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/ANLA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.AUFK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/AUFK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BALDAT
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BALDAT.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BALHDR
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BALHDR.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BDCP2
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BDCP2.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BKPF
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BKPF.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BSAD
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BSAD.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BSAK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BSAK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BSAS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BSAS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BSEG
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BSEG.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BSID
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BSID.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.BSIK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/BSIK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CDHDR
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CDHDR.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CDPOS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CDPOS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CE1XXXX
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CE1XXXX.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CE2XXXX
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CE2XXXX.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.COBK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/COBK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.COEP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/COEP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.COSP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/COSP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.COSS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/COSS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CRHD
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CRHD.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CRTX
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CRTX.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CSKA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CSKA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CSKB
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CSKB.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CSKS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CSKS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CSKT
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CSKT.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.CSKU
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/CSKU.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.DD02L
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/DD02L.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.DD02T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/DD02T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.DD03L
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/DD03L.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.DD03T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/DD03T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EBAN
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EBAN.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EDID4
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EDID4.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EDIDC
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EDIDC.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EINA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EINA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EINE
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EINE.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EKBE
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EKBE.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EKET
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EKET.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EKKO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EKKO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.EKPO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/EKPO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.FAGLFLEXA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/FAGLFLEXA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.HRP1000
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/HRP1000.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.HRP1001
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/HRP1001.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.HRP1002
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/HRP1002.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.INFO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/INFO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.JEST
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/JEST.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.KEKO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/KEKO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.KEPH
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/KEPH.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.KNA1
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/KNA1.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.KNVV
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/KNVV.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.KONV
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/KONV.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LAGP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LAGP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LEIN
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LEIN.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LFA1
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LFA1.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LFB1
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LFB1.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LFM1
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LFM1.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LIKP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LIKP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LIPS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LIPS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LQUA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LQUA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LTAK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LTAK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LTAP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LTAP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LTBK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LTBK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.LTBP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/LTBP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MAKT
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MAKT.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MAPL
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MAPL.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MARA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MARA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MARC
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MARC.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MARD
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MARD.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MAST
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MAST.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MDKP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MDKP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MDTB
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MDTB.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MKPF
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MKPF.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MLCD
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MLCD.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.MSEG
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/MSEG.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.OBJK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/OBJK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA0000
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA0000.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA0001
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA0001.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA0002
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA0002.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA0006
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA0006.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA0007
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA0007.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA0008
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA0008.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA0014
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA0014.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA0015
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA0015.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA2001
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA2001.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA2002
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA2002.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PA2006
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PA2006.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PBED
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PBED.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PBIM
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PBIM.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PLAF
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PLAF.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PLKO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PLKO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.PLPO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/PLPO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.QMEL
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/QMEL.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.RBKP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/RBKP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.RESB
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/RESB.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.RLGRAP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/RLGRAP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.RSEG
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/RSEG.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.SER01
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/SER01.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.STKO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/STKO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.STPO
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/STPO.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T000
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T000.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T000T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T000T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T001L
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T001L.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T001W
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T001W.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T156
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T156.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T156T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T156T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T161
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T161.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T161T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T161T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T300
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T300.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T300T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T300T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T527X
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T527X.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T529T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T529T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T552T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T552T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T554T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T554T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T556T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T556T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T685
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T685.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.T685T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/T685T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TBDLS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TBDLS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TCURC
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TCURC.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TCURT
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TCURT.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TCURX
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TCURX.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TJ02
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TJ02.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TJ02T
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TJ02T.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TKA01
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TKA01.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TKT01
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TKT01.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TTDS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TTDS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TTDST
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TTDST.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TVAK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TVAK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TVAKT
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TVAKT.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TVAP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TVAP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TVAPT
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TVAPT.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TVLK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TVLK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.TVLKT
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/TVLKT.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.USR02
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/USR02.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBAK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBAK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBAP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBAP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBEP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBEP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBFA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBFA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBKD
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBKD.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBPA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBPA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBRK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBRK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBRP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBRP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBUK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBUK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VBUP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VBUP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VFKN
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VFKN.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VFKP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VFKP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VTFA
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VTFA.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VTTK
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VTTK.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VTTP
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VTTP.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

COPY INTO SAP.SAP_ECC.VTTS
    FROM '@USER$.PUBLIC."mbr_snowflake_dbt_ai"/versions/live/sap/data/VTTS.csv'
    FILE_FORMAT = SAP.SAP_ECC.SAP_CSV_FORMAT
    ON_ERROR = 'CONTINUE';

