SELECT
    m.MATERIAL_NUMBER,
    m.MATERIAL_DESCRIPTION,
    m.MATERIAL_TYPE,
    m.MATERIAL_GROUP,
    m.BASE_UNIT_OF_MEASURE,
    m.GROSS_WEIGHT,
    m.WEIGHT_UNIT,
    m.DIVISION,
    m.PRODUCT_HIERARCHY,
    mp.PLANT,
    mp.MRP_TYPE,
    mp.MRP_CONTROLLER,
    mp.PROCUREMENT_TYPE,
    mp.SPECIAL_PROCUREMENT
FROM {{ ref('materials') }} m
LEFT JOIN {{ ref('material_plant_data') }} mp
    ON m.MATERIAL_NUMBER = mp.MATERIAL_NUMBER
