SELECT
    DOCUMENT_NUMBER,
    FISCAL_YEAR,
    POSTING_DATE,
    DOCUMENT_DATE,
    USER_NAME,
    ITEM_NUMBER,
    MOVEMENT_TYPE,
    MATERIAL_NUMBER,
    PLANT,
    STORAGE_LOCATION,
    QUANTITY,
    UNIT_OF_MEASURE,
    AMOUNT_LC AS LOCAL_AMOUNT,
    CURRENCY
FROM {{ ref('goods_movements') }}
