SELECT
    h.DELIVERY_NUMBER,
    h.DELIVERY_TYPE,
    h.CUSTOMER_NUMBER AS SHIP_TO_CUSTOMER,
    h.PLANNED_GOODS_ISSUE_DATE,
    i.ITEM_NUMBER,
    i.MATERIAL_NUMBER,
    i.DELIVERY_QUANTITY,
    i.UNIT_OF_MEASURE,
    i.PLANT
FROM {{ ref('deliveries') }} h
JOIN {{ ref('delivery_items') }} i
    ON h.DELIVERY_NUMBER = i.DELIVERY_NUMBER
