SELECT
    h.PURCHASE_ORDER_NUMBER,
    h.DOCUMENT_TYPE,
    h.VENDOR_NUMBER,
    h.PURCHASING_ORGANIZATION,
    h.PURCHASING_GROUP,
    h.CURRENCY,
    h.ORDER_DATE,
    i.ITEM_NUMBER,
    i.MATERIAL_NUMBER,
    i.PLANT,
    i.ORDER_QUANTITY,
    i.NET_PRICE,
    i.PRICE_UNIT,
    i.NET_VALUE AS ITEM_NET_VALUE
FROM {{ ref('purchase_orders') }} h
JOIN {{ ref('purchase_order_items') }} i
    ON h.PURCHASE_ORDER_NUMBER = i.PURCHASE_ORDER_NUMBER
