SELECT
    h.SALES_ORDER_NUMBER,
    h.DOCUMENT_TYPE_CODE AS ORDER_TYPE,
    h.SALES_ORGANIZATION,
    h.DISTRIBUTION_CHANNEL,
    h.DIVISION,
    h.CUSTOMER_NUMBER AS SOLD_TO_CUSTOMER,
    h.ORDER_DATE,
    h.ORDER_NET_VALUE,
    h.CURRENCY,
    i.ITEM_NUMBER,
    i.MATERIAL_NUMBER,
    i.ORDER_QUANTITY,
    i.UNIT_OF_MEASURE,
    i.NET_VALUE AS ITEM_NET_VALUE,
    i.PLANT,
    s.SCHEDULE_LINE_NUMBER,
    s.CONFIRMED_QUANTITY,
    s.DELIVERY_DATE AS REQUESTED_DELIVERY_DATE
FROM {{ ref('sales_orders') }} h
JOIN {{ ref('sales_order_items') }} i
    ON h.SALES_ORDER_NUMBER = i.SALES_ORDER_NUMBER
LEFT JOIN {{ ref('sales_order_schedules') }} s
    ON i.SALES_ORDER_NUMBER = s.SALES_ORDER_NUMBER
    AND i.ITEM_NUMBER = s.ITEM_NUMBER
