SELECT
    h.BILLING_DOCUMENT_NUMBER,
    h.BILLING_TYPE,
    h.PAYER_CUSTOMER AS CUSTOMER_NUMBER,
    h.BILLING_DATE,
    h.NET_VALUE AS HEADER_NET_VALUE,
    h.CURRENCY,
    i.ITEM_NUMBER,
    i.MATERIAL_NUMBER,
    i.BILLING_QUANTITY,
    i.UNIT_OF_MEASURE,
    i.NET_VALUE AS ITEM_NET_VALUE
FROM {{ ref('billing_documents') }} h
JOIN {{ ref('billing_document_items') }} i
    ON h.BILLING_DOCUMENT_NUMBER = i.BILLING_DOCUMENT_NUMBER
