SELECT
    po.ORDER_NUMBER,
    po.MATERIAL_NUMBER,
    po.ORDER_QUANTITY AS PLANNED_QUANTITY,
    po.UNIT_OF_MEASURE,
    po.PLANT,
    po.PLANNED_START_DATE,
    po.PLANNED_FINISH_DATE,
    r.MATERIAL_NUMBER AS COMPONENT_MATERIAL,
    r.REQUIREMENT_QUANTITY AS PLANNED_COMPONENT_QTY,
    r.UNIT_OF_MEASURE AS COMPONENT_UNIT
FROM {{ ref('production_order_items') }} po
LEFT JOIN {{ ref('production_reservations') }} r
    ON po.ORDER_NUMBER = r.ORDER_NUMBER
